affine_trainable: false
auto_save: true
base_fun_name: !!python/name:torch.sin ''
ckpt_path: ./model
device: cuda
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 3
symbolic.funs_name.0:
- - x
  - x
  - x
  - '0'
  - x^2
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - x
  - '0'
  - x
  - '0'
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - x
  - '0'
  - x
  - '0'
  - x
  - '0'
  - x
  - x
  - x
  - x
  - cos
  - x
  - x
  - sin
  - cos
  - x
  - x
  - x
  - sin
  - x
  - exp
  - x
  - sin
  - x
  - sin
  - x
  - x
- - x
  - x
  - '0'
  - '0'
  - x
  - x
  - '0'
  - '0'
  - x
  - x
  - '0'
  - x
  - x
  - '0'
  - '0'
  - x
  - x
  - '0'
  - x
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - sin
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - cos
  - x
  - x
  - x
  - x
  - x^2
  - sin
  - x
  - '0'
  - cos
  - sin
  - sin
  - x
  - '0'
  - cos
  - x
  - sin
  - x
  - sin
  - cos
  - sin
  - x
  - x
- - x
  - x
  - '0'
  - x
  - x
  - x
  - '0'
  - '0'
  - x
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
  - x
  - x
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - sin
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - x
  - x
  - '0'
  - x
  - x
  - exp
  - x
  - cos
  - cos
  - x
  - x
  - x
  - cos
  - sin
  - x
  - x
  - cos
  - x
  - '0'
  - x
  - cos
  - x
  - sin
  - x
  - x
- - '0'
  - x
  - x
  - x
  - '0'
  - '0'
  - x
  - x
  - '0'
  - x
  - x
  - x
  - '0'
  - x
  - '0'
  - x
  - '0'
  - x
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - x
  - x
  - x
  - x
  - cos
  - x
  - '0'
  - x
  - x
  - sin
  - sin
  - x
  - cos
  - sin
  - x
  - x^2
  - x
  - cos
  - x
  - x
  - x
  - x
- - x
  - x
  - '0'
  - '0'
  - x
  - x
  - '0'
  - '0'
  - x
  - x
  - x
  - '0'
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - '0'
  - '0'
  - x
  - x
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - x
  - x
  - x
  - '0'
  - x
  - x
  - x
  - cos
  - sin
  - x
  - x
  - sqrt
  - cos
  - x
  - x
  - sin
  - cos
  - '0'
  - exp
  - x
  - sin
  - cos
  - sin
  - x
  - '0'
symbolic_enabled: true
width:
- - 60
  - 0
- - 5
  - 0
