# -*- coding: utf-8 -*-
"""Adaptive-Kuramoto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJKkPonr1eMkd3-yRiQ1e_pUcNMonxlW
"""

!pip install pykan

import numpy as np
import torch
from functools import reduce
from torch.optim import Optimizer
import kan.LBFGS as LBFGS


def fit(
    model, dataset, opt="LBFGS", steps=100, log=1,
    lamb=0., lamb_l1=1., lamb_entropy=2., lamb_coef=0., lamb_coefdiff=0.,
    update_grid=True, grid_update_num=10, loss_fn=None, lr=1.,
    start_grid_update_step=-1, stop_grid_update_step=50, batch=-1, metrics=None,
    in_vars=None, out_vars=None, beta=3, singularity_avoiding=False, y_th=1000.,
    reg_metric='edge_forward_spline_n', display_metrics=None, k=1,

    # ---- NEW: integrated rollout loss ------------------------------------------
    rollout_weight=0.0,          # set >0 to enable integration loss
    rollout_horizon=None,        # int number of steps (<= T-1). None => use full T-1
    traj_batch=-1,               # how many trajectories per step (-1 => all)
    dynamics_fn=None,            # optional: f(state)->dstate/dt. defaults to model.forward(state)
    integrator="rk4",            # "euler" or "rk4"
):
    """
    Adds an optional differentiable integration loss:
        if dataset contains 'train_traj' and 'train_t' and rollout_weight>0,
        we integrate ds/dt = f_theta(s) and match predicted states to train_traj.

    Notes:
    - This assumes the model maps STATE -> DERIVATIVE for the rollout term.
      If your model needs feature transforms (Theta, normalization, etc.),
      pass a custom dynamics_fn(state) that does that and returns dstate/dt.
    """

    assert k >= 1, "k must be >= 1"

    # -------------------------------------------------------------------------
    # Original k-step forward (kept for backward compatibility)
    # -------------------------------------------------------------------------
    def k_step_forward(inputs):
        state = inputs
        for _ in range(k):
            state = model.forward(state, singularity_avoiding=singularity_avoiding, y_th=y_th)
        return state

    # -------------------------------------------------------------------------
    # NEW: dynamics function for ODE rollout
    # -------------------------------------------------------------------------
    if dynamics_fn is None:
        def dynamics_fn(state):
            # default: treat model.forward(state) as f_theta(state)
            return model.forward(state, singularity_avoiding=singularity_avoiding, y_th=y_th)

    # Differentiable integrators (batch-safe)
    def euler_step(s, dt):
        return s + dt * dynamics_fn(s)

    def rk4_step(s, dt):
        k1 = dynamics_fn(s)
        k2 = dynamics_fn(s + 0.5 * dt * k1)
        k3 = dynamics_fn(s + 0.5 * dt * k2)
        k4 = dynamics_fn(s + dt * k3)
        return s + (dt / 6.0) * (k1 + 2*k2 + 2*k3 + k4)

    def integrate_states(s0, t):
        """
        s0: (B, state_dim)
        t:  (B, T) or (T,)
        returns: pred_traj (B, T, state_dim)
        """
        if t.dim() == 1:
            # broadcast to (B,T)
            t = t.unsqueeze(0).expand(s0.shape[0], -1)
        B, T = t.shape
        state = s0
        out = [state]

        H = T - 1 if rollout_horizon is None else min(rollout_horizon, T - 1)

        for i in range(H):
            dt = (t[:, i+1] - t[:, i]).unsqueeze(1)  # (B,1)
            if integrator.lower() == "euler":
                state = euler_step(state, dt)
            elif integrator.lower() == "rk4":
                state = rk4_step(state, dt)
            else:
                raise ValueError(f"Unknown integrator: {integrator}")
            out.append(state)

        # If horizon < T-1, we only return the integrated prefix
        pred = torch.stack(out, dim=1)  # (B, H+1, state_dim)
        return pred

    # -------------------------------------------------------------------------
    # Symbolics & activation saving logic (unchanged)
    # -------------------------------------------------------------------------
    if lamb > 0. and not model.save_act:
        print("setting lamb=0. If you want lamb>0, set model.save_act=True")
    old_save_act, old_symbolic_enabled = model.disable_symbolic_in_fit(lamb)

    # -------------------------------------------------------------------------
    # Loss fn
    # -------------------------------------------------------------------------
    if loss_fn is None:
        loss_fn = loss_fn_eval = lambda x, y: torch.mean((x - y) ** 2)
    else:
        loss_fn = loss_fn_eval = loss_fn

    # -------------------------------------------------------------------------
    # Grid update frequency
    # -------------------------------------------------------------------------
    grid_update_freq = max(1, int(stop_grid_update_step / grid_update_num))

    # -------------------------------------------------------------------------
    # Optimizer
    # -------------------------------------------------------------------------
    if opt == "Adam":
        optimizer = torch.optim.Adam(model.get_params(), lr=lr)
    else:
        optimizer = LBFGS(
            model.get_params(), lr=lr, history_size=10,
            line_search_fn="strong_wolfe",
            tolerance_grad=1e-32, tolerance_change=1e-32, tolerance_ys=1e-32
        )

    # -------------------------------------------------------------------------
    # Tracking
    # -------------------------------------------------------------------------
    results = dict(train_loss=[], test_loss=[], reg=[], rollout_train_loss=[], rollout_test_loss=[])
    if metrics is not None:
        for m in metrics:
            results[m.__name__] = []

    # -------------------------------------------------------------------------
    # Batching for derivative supervision (unchanged)
    # -------------------------------------------------------------------------
    n_train = dataset['train_input'].shape[0]
    n_test  = dataset['test_input'].shape[0]
    batch_size      = n_train if batch == -1 or batch > n_train else batch
    batch_size_test = n_test  if batch == -1 or batch > n_test  else batch

    # -------------------------------------------------------------------------
    # Batching for trajectories (new)
    # -------------------------------------------------------------------------
    has_train_traj = ('train_traj' in dataset) and ('train_t' in dataset)
    has_test_traj  = ('test_traj' in dataset) and ('test_t' in dataset)

    if has_train_traj:
        n_traj_train = dataset['train_traj'].shape[0]
        traj_batch_size = n_traj_train if traj_batch == -1 or traj_batch > n_traj_train else traj_batch
    else:
        n_traj_train = 0
        traj_batch_size = 0

    if has_test_traj:
        n_traj_test = dataset['test_traj'].shape[0]
        traj_batch_size_test = n_traj_test if traj_batch == -1 or traj_batch > n_traj_test else traj_batch
    else:
        n_traj_test = 0
        traj_batch_size_test = 0

    global train_loss, reg_, rollout_train_loss

    # -------------------------------------------------------------------------
    # Helper to compute rollout loss on a batch of trajectories
    # -------------------------------------------------------------------------
    def _rollout_loss_on_batch(traj, t):
        """
        traj: (B, T, state_dim) true
        t:    (T,) or (B, T)
        """
        s0 = traj[:, 0, :]                  # (B, state_dim)
        pred = integrate_states(s0, t)      # (B, H+1, state_dim)
        true = traj[:, :pred.shape[1], :]   # align horizons
        return loss_fn(pred, true)

    def rollout_loss_on_batch(traj, t):
        s0 = traj[:, 0, :]
        pred = integrate_states(s0, t)
        true = traj[:, :pred.shape[1], :]
        # angle-aware loss:
        diff = wrap_pi_torch(pred - true)
        return torch.mean(diff**2)

    def order_param_torch(theta):   # theta: (B,T,N)
        z = torch.exp(1j*theta)
        r = torch.abs(torch.mean(z, dim=2))  # (B,T)
        return r.real

    # -------------------------------------------------------------------------
    # LBFGS closure (updated to include rollout term)
    # -------------------------------------------------------------------------
    def closure():
        global train_loss, reg_, rollout_train_loss
        optimizer.zero_grad()

        # --- derivative supervision (your current behavior)
        pred = k_step_forward(dataset['train_input'][train_id])
        train_loss = loss_fn(pred, dataset['train_label'][train_id])

        # --- integrated rollout loss (new)
        if rollout_weight > 0.0 and has_train_traj:
            traj = dataset['train_traj'][traj_id]
            tt   = dataset['train_t']
            rollout_train_loss = rollout_loss_on_batch(traj, tt)
        else:
            rollout_train_loss = torch.tensor(0.0, device=pred.device)

        # --- reg (unchanged)
        if model.save_act:
            if reg_metric == "edge_backward": model.attribute()
            if reg_metric == "node_backward": model.node_attribute()
            reg_ = model.get_reg(reg_metric, lamb_l1, lamb_entropy, lamb_coef, lamb_coefdiff)
        else:
            reg_ = torch.tensor(0., device=pred.device)

        # order_parameter = order_param_torch(traj_kan)

        obj = train_loss + rollout_weight * rollout_train_loss + lamb * reg_
        obj.backward()
        return obj


    # -------------------------------------------------------------------------
    # MAIN LOOP
    # -------------------------------------------------------------------------
    r_weight = 0.5   # start small
    train_ptr = 0
    test_ptr = 0
    traj_ptr = 0
    traj_test_ptr = 0

    for step in range(steps):
        # --- derivative batches (unchanged)
        train_id = np.arange(train_ptr, train_ptr + batch_size) % n_train
        train_ptr = (train_ptr + batch_size) % n_train

        test_id = np.arange(test_ptr, test_ptr + batch_size_test) % n_test
        test_ptr = (test_ptr + batch_size_test) % n_test

        # --- trajectory batches (new)
        if has_train_traj and rollout_weight > 0.0:
            traj_id = np.arange(traj_ptr, traj_ptr + traj_batch_size) % n_traj_train
            traj_ptr = (traj_ptr + traj_batch_size) % n_traj_train

        if has_test_traj and rollout_weight > 0.0:
            traj_test_id = np.arange(traj_test_ptr, traj_test_ptr + traj_batch_size_test) % n_traj_test
            traj_test_ptr = (traj_test_ptr + traj_batch_size_test) % n_traj_test

        # --- grid update (unchanged)
        if (step % grid_update_freq == 0 and
            step < stop_grid_update_step and
            step >= start_grid_update_step and
            update_grid):
            model.update_grid(dataset['train_input'][train_id])

        # --- optimizer step
        if opt == "LBFGS":
            optimizer.step(closure)
        else:
            pred = k_step_forward(dataset['train_input'][train_id])
            train_loss = loss_fn(pred, dataset['train_label'][train_id])

            if rollout_weight > 0.0 and has_train_traj:
                traj = dataset['train_traj'][traj_id]
                tt   = dataset['train_t']
                rollout_train_loss = rollout_loss_on_batch(traj, tt)
            else:
                rollout_train_loss = torch.tensor(0.0, device=pred.device)

            if model.save_act:
                if reg_metric == "edge_backward": model.attribute()
                if reg_metric == "node_backward": model.node_attribute()
                reg_ = model.get_reg(reg_metric, lamb_l1, lamb_entropy, lamb_coef, lamb_coefdiff)
            else:
                reg_ = torch.tensor(0., device=pred.device)

            loss = train_loss + rollout_weight * rollout_train_loss + lamb * reg_
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        # --- test evaluation
        with torch.no_grad():
            test_pred = k_step_forward(dataset['test_input'][test_id])
            test_loss = loss_fn_eval(test_pred, dataset['test_label'][test_id])

            if rollout_weight > 0.0 and has_test_traj:
                traj = dataset['test_traj'][traj_test_id]
                tt   = dataset['test_t']
                rollout_test_loss = rollout_loss_on_batch(traj, tt)
            else:
                rollout_test_loss = torch.tensor(0.0, device=test_pred.device)

        # --- metrics (unchanged)
        if metrics is not None:
            for m in metrics:
                results[m.__name__].append(m().item())

        # --- store
        results['train_loss'].append(torch.sqrt(train_loss).cpu().detach().numpy())
        results['test_loss'].append(torch.sqrt(test_loss).cpu().detach().numpy())
        results['rollout_train_loss'].append(torch.sqrt(rollout_train_loss).cpu().detach().numpy())
        results['rollout_test_loss'].append(torch.sqrt(rollout_test_loss).cpu().detach().numpy())
        results['reg'].append(reg_.cpu().detach().numpy())

        if step % log == 0:
            print(
                f"step {step:5d} | "
                f"train {train_loss:.10f} | test {test_loss:.10f} | "
                f"roll_train {rollout_train_loss:.10f} | roll_test {rollout_test_loss:.10f}"
            )

    model.log_history("fit")
    model.symbolic_enabled = old_symbolic_enabled
    return results


def robust_auto_symbolic(
    model,
    *,
    lib,
    a_range=(-10, 10),
    b_range=(-10, 10),
    r2_threshold=0.90,
    weight_simple=0.90,
    topk_edges=64,
    max_total_complexity=None,
    set_others_to_zero=True,
    weight=0.05,
):
    candidates = []

    # --- collect best symbolic candidate per edge ---
    for l in range(len(model.width_in) - 1):
        for i in range(int(model.width_in[l])):
            for j in range(int(model.width_out[l + 1])):
                name, _, r2, c = model.suggest_symbolic(
                    l, i, j,
                    a_range=a_range,
                    b_range=b_range,
                    lib=lib,
                    verbose=False,
                    weight_simple=weight_simple,
                )

                penalty = (weight_simple / (1e-8 + (1.0 - weight_simple + 1e-8))) * c
                score = r2 - weight * penalty

                candidates.append((l, i, j, str(name), float(r2), float(c), float(score)))

    # --- filter + rank ---
    eligible = [d for d in candidates if d[4] >= r2_threshold and d[3] != "0"]
    eligible.sort(key=lambda d: d[6], reverse=True)

    kept = []
    if max_total_complexity is None:
        kept = eligible[:topk_edges]
    else:
        total_c = 0.0
        for d in eligible:
            if len(kept) >= topk_edges:
                break
            if total_c + d[5] <= max_total_complexity:
                kept.append(d)
                total_c += d[5]

    kept_set = {(l, i, j) for (l, i, j, *_ ) in kept}

    # --- apply fixes ---
    for l, i, j, name, *_ in candidates:
        if (l, i, j) in kept_set:
            model.fix_symbolic(l, i, j, name, verbose=False, log_history=False)
        elif set_others_to_zero:
            model.fix_symbolic(l, i, j, "0", verbose=False, log_history=False)

    model.log_history("robust_auto_symbolic")
    return model

# Kuramoto Helpers
import numpy as np


def wrap_angle(x):
    """Map angles to [0, 2π)."""
    return np.mod(x, 2.0 * np.pi)


def kuramoto_order_parameter(phi):
    """Return complex order parameter Z = r e^{iψ} and r."""
    Z = np.mean(np.exp(1j * phi))
    return Z, np.abs(Z)



def simulate_adaptive_kuramoto(
    N: int = 100,
    T: float = 200.0,
    dt: float = 0.01,
    alpha: float = 0.3 * np.pi,
    beta: float = 0.23 * np.pi,
    eps: float = 0.01,
    omega=0.0,
    phi0=None,
    kappa0=None,
    keep_diag_zero: bool = True,
    method: str = "euler",   # "euler" or "rk4"
    store_every: int = 1,
    seed: int | None = 0,
):
    """
    Simulate the adaptive Kuramoto–Sakaguchi model (28)–(29):
        φ̇_i = ω - (1/N) Σ_j κ_ij sin(φ_i - φ_j + α)
        κ̇_ij = -ε (κ_ij + sin(φ_i - φ_j + β))

    Parameters
    ----------
    omega : float or array-like shape (N,)
        Natural frequency ω (scalar) or ω_i (vector). Eq. (28) uses ω; vector is a common extension.
    phi0 : array-like shape (N,), optional
        Initial phases. If None, uniform random in [0, 2π).
    kappa0 : array-like shape (N,N), optional
        Initial coupling weights. If None, start at 0.
    method : "euler" or "rk4"
        Time stepping method.
    store_every : int
        Store every k-th step to reduce memory.
    """
    rng = np.random.default_rng(seed)

    # omega as vector
    if np.isscalar(omega):
        omega = np.full(N, float(omega))
    else:
        omega = np.asarray(omega, dtype=float)
        assert omega.shape == (N,)

    # initial conditions
    if phi0 is None:
        phi = rng.uniform(0.0, 2.0 * np.pi, size=N)
    else:
        phi = np.asarray(phi0, dtype=float).copy()
        assert phi.shape == (N,)
        phi = wrap_angle(phi)

    if kappa0 is None:
        kappa = np.zeros((N, N), dtype=float)
    else:
        kappa = np.asarray(kappa0, dtype=float).copy()
        assert kappa.shape == (N, N)

    if keep_diag_zero:
        np.fill_diagonal(kappa, 0.0)

    n_steps = int(np.round(T / dt))
    n_store = n_steps // store_every + 1

    t_hist = np.empty(n_store, dtype=float)
    phi_hist = np.empty((n_store, N), dtype=float)
    r_hist = np.empty(n_store, dtype=float)

    def rhs(phi, kappa):
        """
        Compute (dphi, dkappa) given current state.
        Vectorized pairwise differences Δ_ij = φ_i - φ_j.
        """
        # Δ_ij = φ_i - φ_j
        dphi_ij = phi[:, None] - phi[None, :]

        # phase dynamics
        interaction = kappa * np.sin(dphi_ij + alpha)      # κ_ij sin(φ_i - φ_j + α)
        dphi = omega - (1.0 / N) * np.sum(interaction, axis=1)

        # coupling adaptation
        dkappa = -eps * (kappa + np.sin(dphi_ij + beta))

        if keep_diag_zero:
            # enforce κ_ii = 0 and κ̇_ii = 0 (often used; Eq. (29) doesn't forbid self-coupling)
            np.fill_diagonal(dkappa, 0.0)

        return dphi, dkappa

    def step_euler(phi, kappa):
        dphi, dkappa = rhs(phi, kappa)
        phi_new = wrap_angle(phi + dt * dphi)
        kappa_new = kappa + dt * dkappa
        if keep_diag_zero:
            np.fill_diagonal(kappa_new, 0.0)
        return phi_new, kappa_new

    def step_rk4(phi, kappa):
        dphi1, dk1 = rhs(phi, kappa)
        p2 = wrap_angle(phi + 0.5 * dt * dphi1)
        k2 = kappa + 0.5 * dt * dk1

        dphi2, dk2 = rhs(p2, k2)
        p3 = wrap_angle(phi + 0.5 * dt * dphi2)
        k3 = kappa + 0.5 * dt * dk2

        dphi3, dk3 = rhs(p3, k3)
        p4 = wrap_angle(phi + dt * dphi3)
        k4 = kappa + dt * dk3

        dphi4, dk4 = rhs(p4, k4)

        phi_new = wrap_angle(phi + (dt / 6.0) * (dphi1 + 2*dphi2 + 2*dphi3 + dphi4))
        kappa_new = kappa + (dt / 6.0) * (dk1 + 2*dk2 + 2*dk3 + dk4)
        if keep_diag_zero:
            np.fill_diagonal(kappa_new, 0.0)
        return phi_new, kappa_new

    stepper = step_euler if method.lower() == "euler" else step_rk4

    # store initial
    idx = 0
    t_hist[idx] = 0.0
    phi_hist[idx] = phi
    _, r_hist[idx] = kuramoto_order_parameter(phi)

    for n in range(1, n_steps + 1):
        phi, kappa = stepper(phi, kappa)

        if (n % store_every) == 0:
            idx += 1
            t_hist[idx] = n * dt
            phi_hist[idx] = phi
            _, r_hist[idx] = kuramoto_order_parameter(phi)

    return {
        "t": t_hist,
        "phi": phi_hist,
        "r": r_hist,
        "kappa_final": kappa,
    }


## Model Parameters
N = 10
rng = np.random.default_rng(0)
kappa0 = np.ones((N, N)) * 0.5 # Initial Coupling. Set to 0 for none.
np.fill_diagonal(kappa0, 0)
omega = rng.normal(0, 0.1, size=N) # Frequencies

out = simulate_adaptive_kuramoto(
    N=10, T=400.0, dt=0.02,
    #kappa0=kappa0,
    alpha=0.0, # 0.3 * np.pi,
    beta=-0.5, #0.23 * np.pi,
    omega=omega,#0.0,
    method="rk4", store_every=5, seed=1,
)

import numpy as np


def wrap_angle(x):
    """Map angles to [0, 2π)."""
    return np.mod(x, 2.0 * np.pi)


def kuramoto_order_parameter(phi):
    """Return complex order parameter Z = r e^{iψ} and r."""
    Z = np.mean(np.exp(1j * phi))
    return Z, np.abs(Z)



def simulate_adaptive_kuramoto(
    N: int = 100,
    T: float = 200.0,
    dt: float = 0.01,
    alpha: float = 0.3 * np.pi,
    beta: float = 0.23 * np.pi,
    eps: float = 0.01,
    omega=0.0,
    phi0=None,
    kappa0=None,
    keep_diag_zero: bool = True,
    method: str = "euler",   # "euler" or "rk4"
    store_every: int = 1,
    seed: int | None = 0,
):
    """
    Simulate the adaptive Kuramoto–Sakaguchi model (28)–(29):
        φ̇_i = ω - (1/N) Σ_j κ_ij sin(φ_i - φ_j + α)
        κ̇_ij = -ε (κ_ij + sin(φ_i - φ_j + β))

    Parameters
    ----------
    omega : float or array-like shape (N,)
        Natural frequency ω (scalar) or ω_i (vector). Eq. (28) uses ω; vector is a common extension.
    phi0 : array-like shape (N,), optional
        Initial phases. If None, uniform random in [0, 2π).
    kappa0 : array-like shape (N,N), optional
        Initial coupling weights. If None, start at 0.
    method : "euler" or "rk4"
        Time stepping method.
    store_every : int
        Store every k-th step to reduce memory.
    """
    rng = np.random.default_rng(seed)

    # omega as vector
    if np.isscalar(omega):
        omega = np.full(N, float(omega))
    else:
        omega = np.asarray(omega, dtype=float)
        assert omega.shape == (N,)

    # initial conditions
    if phi0 is None:
        phi = rng.uniform(0.0, 2.0 * np.pi, size=N)
    else:
        phi = np.asarray(phi0, dtype=float).copy()
        assert phi.shape == (N,)
        phi = wrap_angle(phi)

    if kappa0 is None:
        kappa = np.zeros((N, N), dtype=float)
    else:
        kappa = np.asarray(kappa0, dtype=float).copy()
        assert kappa.shape == (N, N)

    if keep_diag_zero:
        np.fill_diagonal(kappa, 0.0)

    n_steps = int(np.round(T / dt))
    n_store = n_steps // store_every + 1

    t_hist = np.empty(n_store, dtype=float)
    phi_hist = np.empty((n_store, N), dtype=float)
    r_hist = np.empty(n_store, dtype=float)

    def rhs(phi, kappa):
        """
        Compute (dphi, dkappa) given current state.
        Vectorized pairwise differences Δ_ij = φ_i - φ_j.
        """
        # Δ_ij = φ_i - φ_j
        dphi_ij = phi[:, None] - phi[None, :]

        # phase dynamics
        interaction = kappa * np.sin(dphi_ij + alpha)      # κ_ij sin(φ_i - φ_j + α)
        dphi = omega - (1.0 / N) * np.sum(interaction, axis=1)

        # coupling adaptation
        dkappa = -eps * (kappa + np.sin(dphi_ij + beta))

        if keep_diag_zero:
            # enforce κ_ii = 0 and κ̇_ii = 0 (often used; Eq. (29) doesn't forbid self-coupling)
            np.fill_diagonal(dkappa, 0.0)

        return dphi, dkappa

    def step_euler(phi, kappa):
        dphi, dkappa = rhs(phi, kappa)
        phi_new = wrap_angle(phi + dt * dphi)
        kappa_new = kappa + dt * dkappa
        if keep_diag_zero:
            np.fill_diagonal(kappa_new, 0.0)
        return phi_new, kappa_new

    def step_rk4(phi, kappa):
        dphi1, dk1 = rhs(phi, kappa)
        p2 = wrap_angle(phi + 0.5 * dt * dphi1)
        k2 = kappa + 0.5 * dt * dk1

        dphi2, dk2 = rhs(p2, k2)
        p3 = wrap_angle(phi + 0.5 * dt * dphi2)
        k3 = kappa + 0.5 * dt * dk2

        dphi3, dk3 = rhs(p3, k3)
        p4 = wrap_angle(phi + dt * dphi3)
        k4 = kappa + dt * dk3

        dphi4, dk4 = rhs(p4, k4)

        phi_new = wrap_angle(phi + (dt / 6.0) * (dphi1 + 2*dphi2 + 2*dphi3 + dphi4))
        kappa_new = kappa + (dt / 6.0) * (dk1 + 2*dk2 + 2*dk3 + dk4)
        if keep_diag_zero:
            np.fill_diagonal(kappa_new, 0.0)
        return phi_new, kappa_new

    stepper = step_euler if method.lower() == "euler" else step_rk4

    # store initial
    idx = 0
    t_hist[idx] = 0.0
    phi_hist[idx] = phi
    _, r_hist[idx] = kuramoto_order_parameter(phi)

    for n in range(1, n_steps + 1):
        phi, kappa = stepper(phi, kappa)

        if (n % store_every) == 0:
            idx += 1
            t_hist[idx] = n * dt
            phi_hist[idx] = phi
            _, r_hist[idx] = kuramoto_order_parameter(phi)

    return {
        "t": t_hist,
        "phi": phi_hist,
        "r": r_hist,
        "kappa_final": kappa,
    }


out = simulate_adaptive_kuramoto(
        N=100,
        T=400.0,
        dt=0.02,
        # eps=0.01,
        # alpha=0.3*np.pi,
        # beta=0.23*np.pi,
        alpha=0.0, beta=-0.5, eps=0.05,
        omega=0.0,
        method="rk4",
        store_every=5,
        seed=1,
)

print("Final mean order parameter r:", out["r"][-1])
print("Final κ stats (min/mean/max):",
        out["kappa_final"].min(), out["kappa_final"].mean(), out["kappa_final"].max())

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import CenteredNorm

# ── paste or import your simulation code here ────────────────────────────────
# (wrap_angle, kuramoto_order_parameter, simulate_adaptive_kuramoto)
# then run:

# kappa0 = np.ones((100, 100)) * 0.5
# np.fill_diagonal(kappa0, 0)
# omega = rng.normal(0, 0.1, size=100)
# out = simulate_adaptive_kuramoto(
#     N=100, T=400.0, dt=0.02,
#     #eps=0.01,
#     alpha=0.0, beta=-0.5, eps=0.05,
#     #kappa0=kappa0,
#     #alpha=0.3 * np.pi, beta=0.23 * np.pi,
#     omega=omega,#0.0,
#     method="rk4", store_every=5, seed=1,
# )

t       = out["t"]
phi     = out["phi"]        # (n_store, N)
r       = out["r"]          # (n_store,)
kappa   = out["kappa_final"]  # (N, N)

# ── derived quantities ────────────────────────────────────────────────────────
Z       = np.mean(np.exp(1j * phi), axis=1)   # complex order parameter vs time
psi     = np.angle(Z)                          # mean-field phase ψ(t)
# phases relative to the mean field
phi_rel = np.mod(phi - psi[:, None], 2 * np.pi)

# ── figure layout ─────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(16, 14))
fig.suptitle("Adaptive Kuramoto–Sakaguchi model", fontsize=15, fontweight="bold", y=0.98)

gs = gridspec.GridSpec(3, 3, figure=fig, hspace=0.42, wspace=0.38)

ax_r    = fig.add_subplot(gs[0, :2])   # order parameter r(t)  – wide
ax_circ = fig.add_subplot(gs[0, 2], projection="polar")  # snapshot on circle
ax_rt   = fig.add_subplot(gs[1, :2])   # space-time raster of φ_i(t)
ax_kap  = fig.add_subplot(gs[1, 2])    # final κ heatmap
ax_kdist= fig.add_subplot(gs[2, 0])    # κ_ij distribution
ax_snap = fig.add_subplot(gs[2, 1])    # phase distribution at final time
ax_psi  = fig.add_subplot(gs[2, 2])    # mean-field phase ψ(t)

# ── 1. Order parameter r(t) ───────────────────────────────────────────────────
ax_r.plot(t, r, color="steelblue", lw=1.2)
ax_r.set_xlabel("time $t$")
ax_r.set_ylabel("order parameter $r$")
ax_r.set_title("Kuramoto order parameter $r(t)$")
ax_r.set_ylim(0, 1.05)
ax_r.axhline(r[-50:].mean(), color="tomato", ls="--", lw=1,
             label=f"time-avg (last 10%) = {r[-50:].mean():.3f}")
ax_r.legend(fontsize=9)
ax_r.grid(True, alpha=0.3)

# ── 2. Oscillator phases on unit circle (3 snapshots) ─────────────────────────
snap_indices = [0, len(t) // 2, -1]
snap_colors  = ["#aac4e0", "#5599cc", "#c0392b"]
snap_labels  = [f"t={t[i]:.0f}" for i in snap_indices]

for idx, col, lab in zip(snap_indices, snap_colors, snap_labels):
    angles = phi[idx]
    ax_circ.scatter(angles, np.ones(len(angles)) * 0.85,
                    s=8, alpha=0.6, color=col, label=lab)
    # mean-field arrow
    Zi = np.mean(np.exp(1j * angles))
    ax_circ.annotate("", xy=(np.angle(Zi), np.abs(Zi)),
                     xytext=(0, 0),
                     arrowprops=dict(arrowstyle="->", color=col, lw=1.8),
                     xycoords="data")

ax_circ.set_title("Phase snapshots\n& order vector", fontsize=9)
ax_circ.set_yticks([])
ax_circ.legend(fontsize=7, loc="lower left", bbox_to_anchor=(-0.15, -0.15))

# ── 3. Space-time raster: φ_i(t) mod 2π ──────────────────────────────────────
# subsample oscillators for readability
n_show = min(50, phi.shape[1])
osc_idx = np.linspace(0, phi.shape[1] - 1, n_show, dtype=int)
im = ax_rt.imshow(
    phi[:, osc_idx].T,
    aspect="auto",
    origin="lower",
    extent=[t[0], t[-1], 0, n_show],
    cmap="hsv",
    vmin=0, vmax=2 * np.pi,
)
fig.colorbar(im, ax=ax_rt, label="$\\phi_i$ (rad)", pad=0.02)
ax_rt.set_xlabel("time $t$")
ax_rt.set_ylabel("oscillator index")
ax_rt.set_title("Phase raster $\\phi_i(t)$")

# ── 4. Final coupling matrix κ_ij ────────────────────────────────────────────
im2 = ax_kap.imshow(kappa, aspect="auto", cmap="RdBu_r",
                    norm=CenteredNorm())
fig.colorbar(im2, ax=ax_kap, label="$\\kappa_{ij}$", pad=0.02)
ax_kap.set_title("Final coupling\nmatrix $\\kappa_{ij}$")
ax_kap.set_xlabel("oscillator $j$")
ax_kap.set_ylabel("oscillator $i$")

# ── 5. Distribution of κ_ij (off-diagonal) ───────────────────────────────────
mask = ~np.eye(kappa.shape[0], dtype=bool)
kvals = kappa[mask]
ax_kdist.hist(kvals, bins=60, color="steelblue", edgecolor="white", lw=0.3)
ax_kdist.axvline(kvals.mean(), color="tomato", ls="--", lw=1.2,
                 label=f"mean = {kvals.mean():.3f}")
ax_kdist.set_xlabel("$\\kappa_{ij}$")
ax_kdist.set_ylabel("count")
ax_kdist.set_title("Distribution of\nfinal $\\kappa_{ij}$")
ax_kdist.legend(fontsize=9)
ax_kdist.grid(True, alpha=0.3)

# ── 6. Phase distribution at final time ──────────────────────────────────────
bins = np.linspace(0, 2 * np.pi, 31)
ax_snap.hist(phi[-1], bins=bins, color="mediumseagreen",
             edgecolor="white", lw=0.4)
ax_snap.set_xlabel("$\\phi_i$ (rad)")
ax_snap.set_ylabel("count")
ax_snap.set_title(f"Phase distribution\nat $t={t[-1]:.0f}$")
ax_snap.set_xticks([0, np.pi, 2*np.pi])
ax_snap.set_xticklabels(["0", "$\\pi$", "$2\\pi$"])
ax_snap.grid(True, alpha=0.3)

# ── 7. Mean-field phase ψ(t) ─────────────────────────────────────────────────
ax_psi.plot(t, np.unwrap(psi), color="darkorchid", lw=1.2)
ax_psi.set_xlabel("time $t$")
ax_psi.set_ylabel("$\\psi(t)$ (rad, unwrapped)")
ax_psi.set_title("Mean-field phase $\\psi(t)$")
ax_psi.grid(True, alpha=0.3)

plt.savefig("kuramoto_diagnostics.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved kuramoto_diagnostics.png")

# ============================================================
# KANDY cell — Adaptive Kuramoto–Sakaguchi model.
# KAN predicts dφᵢ/dt only. κ is treated as a known input feature.
# Mirrors the standard Kuramoto cell structure.
# ============================================================

def order_parameter(phi_traj: np.ndarray) -> np.ndarray:
    """
    Kuramoto order parameter r(t) for a phase trajectory.

    Parameters
    ----------
    phi_traj : np.ndarray, shape (T, N) or (N,)
        Phases in radians (can be wrapped or unwrapped; wrapping doesn't matter).

    Returns
    -------
    r : np.ndarray, shape (T,)  (or scalar if input is (N,))
        r(t) = | (1/N) * sum_j exp(i * phi_j(t)) |
    """
    phi_traj = np.asarray(phi_traj)
    if phi_traj.ndim == 1:  # (N,)
        return np.abs(np.mean(np.exp(1j * phi_traj)))
    elif phi_traj.ndim == 2:  # (T,N)
        return np.abs(np.mean(np.exp(1j * phi_traj), axis=1))
    else:
        raise ValueError(f"phi_traj must have shape (N,) or (T,N), got {phi_traj.shape}")

# ── 0. Simulation data ────────────────────────────────────────────────────────
# out_dense = simulate_adaptive_kuramoto(
#     N=10,
#     T=200.0,
#     dt=0.02,
#     eps=0.01,
#     alpha=0.3 * np.pi,
#     beta=0.23 * np.pi,
#     omega=0.0,
#     method="rk4",
#     store_every=1,
#     seed=42,
# )
rng = np.random.default_rng(0)
kappa0 = np.ones((10, 10)) * 0.5
np.fill_diagonal(kappa0, 0)
omega = rng.normal(0, 0.1, size=10)
out_dense = simulate_adaptive_kuramoto(
    N=5, T=400.0, dt=0.02,
    eps=0.01,
    #alpha=0.0, beta=-0.5, eps=0.05,
    #kappa0=kappa0,
    alpha=0.3 * np.pi, beta=0.23 * np.pi,
    omega=0.0,
    method="rk4", store_every=5, seed=1,
)
N_osc     = 5
dt_sim    = 0.02
alpha     = 0.3 * np.pi
beta      = 0.23 * np.pi
eps       = 0.01
omega_vec = np.zeros(N_osc, dtype=np.float64)

phi_traj = out_dense["phi"]      # (n_store, N)

# ── 1. Reconstruct κ trajectory ───────────────────────────────────────────────
n_store    = phi_traj.shape[0]
kappa_traj = np.zeros((n_store, N_osc, N_osc), dtype=np.float64)

dt_store = dt_sim * 5 ### change
for s in range(n_store - 1):
    phi_s   = phi_traj[s]
    k_s     = kappa_traj[s]
    dphi_ij = phi_s[:, None] - phi_s[None, :]
    dkappa  = -eps * (k_s + np.sin(dphi_ij + beta))
    np.fill_diagonal(dkappa, 0.0)
    kappa_traj[s + 1] = k_s + dt_store * dkappa

off_mask = ~np.eye(N_osc, dtype=bool)

# ── 2. Features and targets ───────────────────────────────────────────────────
# Features: [phase diffs Δᵢⱼ (N*(N-1)),  off-diag κᵢⱼ (N*(N-1))]
# Target:   dφᵢ/dt  (N,)  — same as standard Kuramoto cell

def build_features(phi_t, kappa_t):
    dphi_ij   = wrap_pi(phi_t[:, None] - phi_t[None, :])
    diffs_off = dphi_ij[off_mask]      # N*(N-1)
    kappa_off = kappa_t[off_mask]      # N*(N-1)
    return np.concatenate([diffs_off, kappa_off]).astype(np.float32)

def compute_dphi(phi_t, kappa_t):
    dphi_ij     = phi_t[:, None] - phi_t[None, :]
    interaction = kappa_t * np.sin(dphi_ij + alpha)
    return (omega_vec - (1.0 / N_osc) * interaction.sum(axis=1)).astype(np.float32)



X_list, y_list = [], []
for s in range(1, n_store - 1):   # central difference window
    X_list.append(build_features(phi_traj[s], kappa_traj[s]))
    y_list.append(compute_dphi(phi_traj[s], kappa_traj[s]))

X_np = np.stack(X_list)   # (T_eff, 2*N*(N-1))
y_np = np.stack(y_list)   # (T_eff, N)          ← N outputs only

print(f"Feature dim : {X_np.shape[1]}  ( = 2 * N*(N-1) = 2*{N_osc*(N_osc-1)} )")
print(f"Target dim  : {y_np.shape[1]}  ( = N = {N_osc} )")
print(f"Samples     : {X_np.shape[0]}")

# ── 3. Torch tensors + train/test split ───────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
X_t = torch.tensor(X_np, device=device)
y_t = torch.tensor(y_np, device=device)

perm      = torch.randperm(X_t.shape[0], device=device)
n_test    = int(0.2 * X_t.shape[0])
test_idx  = perm[:n_test]
train_idx = perm[n_test:]

dataset = {
    "train_input": X_t[train_idx],
    "train_label": y_t[train_idx],
    "test_input":  X_t[test_idx],
    "test_label":  y_t[test_idx],
}

# =============================
# Add trajectory tensors for rollout loss (Adaptive Kuramoto)
# State = [phi (N), kappa_off (N*(N-1))]
# =============================

def build_state_traj(phi_traj_np, kappa_traj_np):
    # phi_traj_np:   (T, N)
    # kappa_traj_np: (T, N, N)
    kappa_off = kappa_traj_np[:, off_mask]              # (T, N*(N-1))
    state = np.concatenate([phi_traj_np, kappa_off], axis=1).astype(np.float32)  # (T, N + N*(N-1))
    return state

state_traj_np = build_state_traj(phi_traj, kappa_traj)  # (n_store, state_dim)

# time grid (matches stored samples: store_every=5 => dt_effective = dt_sim*5)
dt_effective = dt_sim * 5
t_np = np.arange(n_store, dtype=np.float32) * dt_effective

state_traj_torch = torch.tensor(state_traj_np, dtype=torch.float32, device=device)  # (T, state_dim)
t_torch = torch.tensor(t_np, dtype=torch.float32, device=device)                    # (T,)

# Split a prefix for rollout training (example: first 60% of the trajectory)
T_train = int(0.6 * n_store)
train_traj = state_traj_torch[:T_train].unsqueeze(0)  # (1, T_train, state_dim)
train_t    = t_torch[:T_train]                        # (T_train,)

# (Optional) test rollout segment
test_traj = state_traj_torch[T_train:].unsqueeze(0)   # (1, T_test, state_dim)
test_t    = t_torch[T_train:]                         # (T_test,)

dataset.update({
    "train_traj": train_traj,
    "train_t":    train_t,
    "test_traj":  test_traj,
    "test_t":     test_t,
})

# =============================
# dynamics_fn for rollout: d/dt [phi, kappa_off]
# =============================

def dynamics_fn(state_b: torch.Tensor) -> torch.Tensor:
    """
    state_b: (B, state_dim) where state_dim = N_osc + N_osc*(N_osc-1)
    returns: (B, state_dim) derivatives [dphi, dkappa_off]
    """
    B = state_b.shape[0]
    N = N_osc
    M = N * (N - 1)

    phi_b = state_b[:, :N]          # (B, N)
    k_off = state_b[:, N:N+M]       # (B, M)

    # --- reconstruct full kappa matrix (B,N,N) from off-diagonal vector ---
    kappa_b = torch.zeros((B, N, N), device=state_b.device, dtype=state_b.dtype)
    mask = torch.tensor(off_mask, device=state_b.device)
    kappa_b[:, mask] = k_off
    # diag remains 0 by construction

    # --- build KAN input features: [diffs_off, kappa_off] ---
    dphi_ij = wrap_pi_torch(phi_b[:, :, None] - phi_b[:, None, :])   # (B,N,N)
    diffs_off = dphi_ij[:, mask]                                      # (B,M)
    X_b = torch.cat([diffs_off, k_off], dim=1)                        # (B, 2M)

    # --- dphi from KAN ---
    dphi_b = kan_adaptive(X_b)                                        # (B, N)

    # --- dkappa from known adaptation law (off-diagonal only) ---
    # dkappa_ij = -eps * (kappa_ij + sin(phi_i - phi_j + beta))
    # note: here dphi_ij uses (i - j); your sim uses phi_i - phi_j, consistent.
    dkappa_b = -eps * (kappa_b + torch.sin(dphi_ij + beta))           # (B,N,N)
    dkappa_off = dkappa_b[:, mask]                                    # (B,M)

    return torch.cat([dphi_b, dkappa_off], dim=1)                     # (B, N+M)

# ── 4. Build KAN ───────────────────────────────────────────────────────────────
F_in  = X_np.shape[1]   # 2 * N*(N-1)
F_out = N_osc           # N  ← just the phases

kan_adaptive = KAN(
    width=[F_in, F_out],
    grid=5,
    k=3,
    base_fun=torch.sin,
    seed=0,
).to(device)

# ── 5. Train ───────────────────────────────────────────────────────────────────
print("\nTraining KAN (predicting dφ/dt)...")
results = fit(
    kan_adaptive,
    dataset,
    opt="LBFGS",
    steps=200,
    log=20,
    #lamb=1e-4,
    lamb=0.0,
    lamb_l1=1.0,
    rollout_weight=1.0,          # set >0 to enable integration loss
    rollout_horizon=10,        # int number of steps (<= T-1). None => use full T-1
    dynamics_fn=dynamics_fn,
    lamb_entropy=2.0,
    update_grid=True,
    stop_grid_update_step=50,
)

# ── 6. Evaluate ───────────────────────────────────────────────────────────────
with torch.no_grad():
    pred_test = kan_adaptive(dataset["test_input"])
    mse = torch.mean((pred_test - dataset["test_label"])**2).item()
print(f"\nTest MSE (dφ/dt): {mse:.6e}")

# ── 7. Rollout ────────────────────────────────────────────────────────────────
# φ is integrated by the KAN; κ is stepped analytically alongside it.

def rhs_kan_adaptive(phi_np, kappa_np):
    """
    phi_np   : (N,)
    kappa_np : (N, N)
    Returns  dφ/dt predicted by the KAN.
    """
    feat = build_features(phi_np, kappa_np)
    s_b  = torch.tensor(feat[None, :], dtype=torch.float32, device=device)
    with torch.no_grad():
        dphi = kan_adaptive(s_b).cpu().numpy().squeeze(0)
    return dphi

def rhs_true_adaptive(phi_np, kappa_np):
    dphi_ij     = phi_np[:, None] - phi_np[None, :]
    interaction = kappa_np * np.sin(dphi_ij + alpha)
    return omega_vec - (1.0 / N_osc) * interaction.sum(axis=1)

def rollout_with_kappa(dphi_fn, phi0, kappa0, T_roll, dt):
    """
    Integrate φ using dphi_fn; step κ analytically in parallel.
    """
    steps = int(T_roll / dt)
    phi_hist   = np.zeros((steps + 1, N_osc))
    kappa_hist = np.zeros((steps + 1, N_osc, N_osc))
    phi_hist[0]   = phi0
    kappa_hist[0] = kappa0

    for k in range(steps):
        phi_k   = phi_hist[k]
        kappa_k = kappa_hist[k]

        # φ step (RK4 using the KAN)
        def f_phi(ph): return dphi_fn(ph, kappa_k)
        k1 = f_phi(phi_k)
        k2 = f_phi(wrap_pi(phi_k + 0.5*dt*k1))
        k3 = f_phi(wrap_pi(phi_k + 0.5*dt*k2))
        k4 = f_phi(wrap_pi(phi_k + dt*k3))
        phi_new = wrap_pi(phi_k + (dt/6.0)*(k1 + 2*k2 + 2*k3 + k4))

        # κ step (Euler, analytical)
        dphi_ij = phi_k[:, None] - phi_k[None, :]
        dkappa  = -eps * (kappa_k + np.sin(dphi_ij + beta))
        np.fill_diagonal(dkappa, 0.0)
        kappa_new = kappa_k + dt * dkappa

        phi_hist[k+1]   = phi_new
        kappa_hist[k+1] = kappa_new

    return phi_hist, kappa_hist

T_rollout = 20.0
phi0_roll   = phi_traj[0].copy()
kappa0_roll = kappa_traj[0].copy()

phi_kan,  kappa_kan  = rollout_with_kappa(rhs_kan_adaptive,  phi0_roll, kappa0_roll, T_rollout, dt_sim)
phi_true, kappa_true = rollout_with_kappa(rhs_true_adaptive, phi0_roll, kappa0_roll, T_rollout, dt_sim)

roll_mse = np.mean(wrap_pi(phi_kan - phi_true)**2)
print(f"Rollout phase MSE (angle-aware, T={T_rollout}): {roll_mse:.4e}")

# ── 8. Plot ───────────────────────────────────────────────────────────────────
time_roll = np.linspace(0, T_rollout, phi_kan.shape[0])
r_kan  = order_parameter(phi_kan)
r_true = order_parameter(phi_true)

fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=True)

ax = axes[0]
for i in range(N_osc):
    ax.plot(time_roll, np.unwrap(phi_kan[:, i]),  lw=1.5, label=f"KAN φ_{i}" if i < 3 else None)
    ax.plot(time_roll, np.unwrap(phi_true[:, i]), lw=1.5, ls="--", alpha=0.5)
ax.set_ylabel("Phase (unwrapped rad)")
ax.set_title("KAN rollout (solid) vs. ground truth (dashed) — φᵢ(t)")
ax.legend(fontsize=8, ncol=3); ax.grid(alpha=0.3)

ax = axes[1]
ax.plot(time_roll, r_kan,  label="KAN r(t)")
ax.plot(time_roll, r_true, "--", label="True r(t)")
ax.set_ylabel("Order parameter r"); ax.set_title("Synchronisation order parameter")
ax.legend(); ax.grid(alpha=0.3)

ax = axes[2]
koff_kan  = kappa_kan[:, off_mask]
koff_true = kappa_true[:, off_mask]
ax.plot(time_roll, koff_kan.mean(axis=1),  label="KAN ⟨κ⟩")
ax.plot(time_roll, koff_true.mean(axis=1), "--", label="True ⟨κ⟩")
ax.fill_between(time_roll, koff_kan.min(axis=1), koff_kan.max(axis=1), alpha=0.15)
ax.set_ylabel("Mean coupling ⟨κᵢⱼ⟩"); ax.set_xlabel("Time")
ax.set_title("Coupling evolution (κ stepped analytically in both cases)")
ax.legend(); ax.grid(alpha=0.3)

plt.tight_layout()
plt.show()

# Loss curves
fig2, ax2 = plt.subplots(figsize=(9, 3))
ax2.semilogy(results["train_loss"], label="train")
ax2.semilogy(results["test_loss"],  label="test")
ax2.set_xlabel("Step"); ax2.set_ylabel("RMSE")
ax2.set_title("KAN training loss — adaptive Kuramoto (dφ/dt only)")
ax2.legend(); ax2.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# ============================================================
# KANDY cell — Regular Kuramoto–Sakaguchi Oscillators.
# KAN predicts dφᵢ/dt.
# ============================================================

import numpy as np
import torch
import matplotlib.pyplot as plt
import networkx as nx
from kan import KAN

# -----------------------------
# Constants + helpers
# -----------------------------
TWOPI = 2 * np.pi

def wrap_pi(x):
    return (x + np.pi) % (2*np.pi) - np.pi

def wrap_pi_torch(x):
    return (x + np.pi) % (2*np.pi) - np.pi

def unwrap_for_plot(traj_wrapped):
    return np.unwrap(traj_wrapped, axis=0)

def rk4_step_vec(f, y, dt, **kwargs):
    k1 = f(y, **kwargs)
    k2 = f(y + 0.5*dt*k1, **kwargs)
    k3 = f(y + 0.5*dt*k2, **kwargs)
    k4 = f(y + dt*k3, **kwargs)
    return y + (dt/6.0)*(k1 + 2*k2 + 2*k3 + k4)

# -----------------------------
# True Kuramoto RHS (ground truth)
# -----------------------------
def kuramoto_rhs(theta, omega, K=1.0, A=None):
    """
    Full Kuramoto RHS:
        dθ_i/dt = ω_i + K * Σ_j A_ij sin(θ_j - θ_i)
    """
    N = theta.shape[0]
    if A is None:
        A = np.ones((N, N), dtype=np.float64) / N
        np.fill_diagonal(A, 0.0)
    diffs = wrap_pi(theta[None, :] - theta[:, None])  # (i,j) = θ_j - θ_i
    coupling = (A * np.sin(diffs)).sum(axis=1)
    return omega + K * coupling

# -----------------------------
# Derivative estimate from a wrapped trajectory
# -----------------------------
def estimate_dtheta_from_traj(traj_wrapped, dt, method="central"):
    # differentiate unwrapped phases to avoid wrap artifacts
    theta_unwrapped = np.unwrap(traj_wrapped, axis=0)
    if method == "forward":
        dtheta = (theta_unwrapped[1:] - theta_unwrapped[:-1]) / dt
        theta_mid = traj_wrapped[:-1]
    elif method == "central":
        dtheta = (theta_unwrapped[2:] - theta_unwrapped[:-2]) / (2.0 * dt)
        theta_mid = traj_wrapped[1:-1]
    else:
        raise ValueError("method must be 'forward' or 'central'")
    return theta_mid, dtheta

# -----------------------------
# FEATURE MAP (IMPORTANT CHANGE)
# -----------------------------
# Model inputs should be the phase difference in theta.
# Since base_fun=torch.sin, KAN will learn the sine of these diffs internally.

def build_features_diff_offdiag(theta_t, A, include_self=False, weight_mode="mul"):
    """
    NumPy features: flattened off-diagonal of raw diffs (θ_j - θ_i).

    """
    N = theta_t.shape[0]
    diffs = wrap_pi(theta_t[None, :] - theta_t[:, None])  # θ_j - θ_i  (i,j)
    if not include_self:
        np.fill_diagonal(diffs, 0.0)

    mask = ~np.eye(N, dtype=bool)
    diffs_off = diffs[mask]  # (N*(N-1),)

    return diffs_off


def build_features_diff_offdiag_torch(theta_b, A_torch, include_self=False):
    """
    Torch features: (B, N) -> (B, N*(N-1)) (or doubled if 'cat')
    diffs[i,j] = θ_j - θ_i, wrapped to [-pi, pi)
    """
    B, N = theta_b.shape
    diffs = wrap_pi_torch(theta_b[:, None, :] - theta_b[:, :, None])  # (B,N,N)

    if not include_self:
        eye = torch.eye(N, device=theta_b.device, dtype=torch.bool)
        diffs = diffs.masked_fill(eye.unsqueeze(0), 0.0)

    mask = ~torch.eye(N, device=theta_b.device, dtype=torch.bool)
    diffs_off = diffs[:, mask]  # (B, N*(N-1))

    return diffs_off


# -----------------------------
# Rollout helper (NumPy) for plotting / evaluation
# -----------------------------
def rollout_rhs(rhs_fn, theta0, T_roll, dt):
    steps_r = int(T_roll / dt)
    tr = np.zeros((steps_r + 1, theta0.shape[0]), dtype=np.float64)
    th = theta0.astype(np.float64).copy()
    tr[0] = th
    for k in range(steps_r):
        th = rk4_step_vec(lambda th_: rhs_fn(th_), th, dt)
        th = wrap_pi(th)
        tr[k + 1] = th
    return tr

def order_parameter(traj):
    return np.abs(np.mean(np.exp(1j * traj), axis=1))

# =============================
# 1) Generate a single trajectory
# =============================
N = 4
T = 50.0
dt = 0.01
steps = int(T / dt)

rng = np.random.default_rng(0)
omega = np.array([0.00, 0.02, -0.01, 0.01], dtype=np.float64)

# Graph / adjacency (you can swap this out)
G = nx.erdos_renyi_graph(N, p=0.4, seed=0)
A = nx.to_numpy_array(G, dtype=float)

# Force global coupling (as you did)
A = np.ones((N, N), dtype=np.float64) / N
np.fill_diagonal(A, 0.0)

K_true = 1.5

theta = rng.uniform(-np.pi, np.pi, size=N)
traj = np.zeros((steps + 1, N), dtype=np.float64)
traj[0] = theta

for k in range(steps):
    theta = rk4_step_vec(kuramoto_rhs, theta, dt, omega=omega, K=K_true, A=A)
    theta = wrap_pi(theta)
    traj[k + 1] = theta

# =========================================
# 2) Supervised dataset: X(theta)->coupling
# =========================================
theta_feat, dtheta = estimate_dtheta_from_traj(traj, dt, method="central")
T_eff = theta_feat.shape[0]

# target = coupling only (includes K_true and adjacency effect)
y_coupling = dtheta - omega[None, :]  # (T_eff, N)

# Inputs are phase differences.
X_list = [build_features_diff_offdiag(theta_feat[k], A=A, include_self=False)
          for k in range(T_eff)]
X_np = np.stack(X_list, axis=0).astype(np.float32)

y_np = y_coupling.astype(np.float32)

# =============================
# 3) Torch tensors + split
# =============================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
X = torch.tensor(X_np, device=device)
y = torch.tensor(y_np, device=device)

Ttot = X.shape[0]
perm = torch.randperm(Ttot, device=device)
T_test = int(0.2 * Ttot)
test_idx = perm[:T_test]
train_idx = perm[T_test:]

# Trajectory tensors for rollout loss (single trajectory -> add batch dim)
theta_traj_torch = torch.tensor(traj, dtype=torch.float32, device=device)  # (steps+1, N)
t_torch = torch.linspace(0.0, T, steps + 1, device=device)

T_train = int(0.6 * (steps + 1))
train_traj = theta_traj_torch[:T_train].unsqueeze(0)   # (1, T_train, N)
train_t    = t_torch[:T_train]                          # (T_train,)

dataset = {
    "train_input": X[train_idx],
    "train_label": y[train_idx],
    "test_input":  X[test_idx],
    "test_label":  y[test_idx],
    "train_traj":  train_traj,
    "train_t":     train_t,
}

# =============================
# 4) Build model
# =============================
F = X.shape[1]  # feature dim depends on weight_mode
base_fun = lambda x: torch.sin(x)  # model learns sine of diffs via base_fun
kan = KAN(width=[F, N], grid=3, k=1, base_fun=base_fun, seed=0).to(device)

A_torch = torch.tensor(A, dtype=torch.float32, device=device)
omega_torch = torch.tensor(omega, dtype=torch.float32, device=device)

def model_coupling(theta_b: torch.Tensor) -> torch.Tensor:
    """
    theta_b: (B, N)
    returns: coupling term only (B, N) = K_true Σ_j A_ij sin(θ_j-θ_i) (learned)
    """
    X_b = build_features_diff_offdiag_torch(
        theta_b, A_torch, include_self=False
    )
    return kan(X_b)

def dynamics_fn(theta_b: torch.Tensor) -> torch.Tensor:
    """
    dynamics for integrator: dθ/dt = ω + coupling(theta)
    Omega is hardcoded and added outside the model.
    """
    return omega_torch.unsqueeze(0) + model_coupling(theta_b)

# =============================
# 5) Train (uses your modified fit)
# =============================
# First, include rollout loss so the model learns to integrate well.
#losses = kan.fit(dataset, steps=100)
# fit(kan,
#     dataset,
#     steps=100,
#     rollout_weight=0.5,          # enable rollout loss
#     rollout_horizon=5,        # None => full horizon within provided train_t
#     dynamics_fn=dynamics_fn,
#     integrator="rk4",
# )

# Then do your standard regression fine-tune (optional)
fit(kan, dataset, steps=200)

with torch.no_grad():
    pred = kan(dataset["test_input"])
    mse = torch.mean((pred - dataset["test_label"])**2).item()
print("test MSE (coupling-only):", mse)

# =============================
# 6) Rollout with learned dynamics (NumPy)
# =============================
def rhs_kan(theta_np):
    """
    theta_np: (N,)
    returns dtheta/dt = omega + coupling_pred
    omega added outside the model (hardcoded)
    """
    theta_b = torch.tensor(theta_np[None, :], dtype=torch.float32, device=device)
    with torch.no_grad():
        coupling_pred = model_coupling(theta_b).detach().cpu().numpy().squeeze(0)
    return omega + coupling_pred

T_rollout = 20.0
theta0_test = traj[0].copy()

traj_kan = rollout_rhs(rhs_kan, theta0_test, T_rollout, dt)

# Ground truth from same IC
def rhs_true(th):
    return kuramoto_rhs(th, omega=omega, K=K_true, A=A)

traj_true = rollout_rhs(rhs_true, theta0_test, T_rollout, dt)

diff = wrap_pi(traj_kan - traj_true)
mse_roll = np.mean(diff**2)
print(f"rollout MSE (angle-aware): {mse_roll:.6e}")

# =============================
# 7) Plot
# =============================
time_rollout = np.linspace(0, T_rollout, traj_kan.shape[0])

traj_kan_u  = unwrap_for_plot(traj_kan)
traj_true_u = unwrap_for_plot(traj_true)

fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

ax = axes[0]
for i in range(N):
    ax.plot(time_rollout, traj_kan_u[:, i], label=f'θ_{i} (KAN)', linewidth=2)
ax.set_ylabel('Phase (unwrapped rad)')
ax.set_title('KAN Rollout (inputs=diffs; learns sin via base_fun; ω hardcoded)', fontweight='bold')
ax.grid(True, alpha=0.3)
ax.legend(loc='best')

ax = axes[1]
for i in range(N):
    ax.plot(time_rollout, traj_true_u[:, i], label=f'θ_{i} (True)', linewidth=2, linestyle='--')
ax.set_xlabel('Time')
ax.set_ylabel('Phase (unwrapped rad)')
ax.set_title('Ground Truth (Kuramoto)', fontweight='bold')
ax.grid(True, alpha=0.3)
ax.legend(loc='best')

plt.tight_layout()
plt.show()

r_kan = order_parameter(traj_kan)
r_true = order_parameter(traj_true)

plt.figure(figsize=(10, 3))
plt.plot(time_rollout, r_kan, label='KAN')
plt.plot(time_rollout, r_true, '--', label='True')
plt.xlabel("Time")
plt.ylabel("r(t)")
plt.title("Kuramoto Order Parameter")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

