# -*- coding: utf-8 -*-
"""Henon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/kslote1/KAN-ICML/blob/main/Henon.ipynb
"""

!pip install pykan --quiet

import numpy as np
import torch
import matplotlib.pyplot as plt
from kan import KAN, add_symbolic
from IPython.display import display, Math
import sympy as sp

seed = 42
rng = np.random.default_rng(seed)
torch.manual_seed(seed)
np.random.seed(seed)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

# Generate Hénon map data
def henon_step(state, a=1.4, b=0.3):
    x, y = state
    x_next = 1 - a * x**2 + y
    y_next = b * x
    return np.array([x_next, y_next], dtype=np.float32)

def generate_henon(n_total=12000, burn_in=1000, x0=0.1, y0=0.0, a=1.4, b=0.3):
    xy = np.zeros((n_total + burn_in, 2), dtype=np.float32)
    xy[0] = [x0, y0]
    for i in range(n_total + burn_in - 1):
        xy[i+1] = henon_step(xy[i], a=a, b=b)
    return xy[burn_in:]

def to_tensor(a):
    return torch.tensor(a, dtype=torch.float32, device=device)

# Params
a, b = 1.4, 0.3
n_samples = 10000
burn_in = 1000
series = generate_henon(n_total=n_samples, burn_in=burn_in, a=a, b=b)

# Temporal split
X = series[:-1]
Y = series[1:]

test_frac = 0.2
val_frac = 0.2
N = len(X)
n_test = int(N * test_frac)
n_val  = int((N - n_test) * val_frac)

X_train = X[:N - n_test - n_val]
Y_train = Y[:N - n_test - n_val]
X_val = X[N - n_test - n_val:N - n_test]
Y_val = Y[N - n_test - n_val:N - n_test]
X_test = X[N - n_test:]
Y_test = Y[N - n_test:]

dataset = {
    "train_input": to_tensor(X_train),
    "train_label": to_tensor(Y_train),
    "val_input":  to_tensor(X_val),
    "val_label":  to_tensor(Y_val),
    "test_input":  to_tensor(X_test),
    "test_label":  to_tensor(Y_test),
}

T_train = (N - n_test - n_val) + 1
train_seq = to_tensor(series[:T_train])
val_seq = to_tensor(series[N - n_test - n_val - 200 : N - n_test + 1])
test_seq = to_tensor(series[N - n_test : ])

# Model
width = [2, 2]
grid  = 10
k_spline = 3

base_fun = lambda x: torch.exp(-x**2)
model = KAN(width=width, grid=5, k=3, base_fun=base_fun, seed=seed).to(device)
model.fit(dataset, steps=2000)
beta = 10
model(dataset['train_input']);
model.plot(beta=beta, in_vars=[r"$x_n$", r"$y_n$"], out_vars=[r"$y_{n+1}$", r"$y_{n+1}$"])
plt.show()

model(dataset['train_input'])
model.auto_symbolic()
exprs, inputs = model.symbolic_formula()

# Parse to SymPy
y1 = sp.sympify(exprs[0])
y2 = sp.sympify(exprs[1])

# Rename vars
x_n, y_n = sp.symbols('x_n y_n')
sub_map = {sp.Symbol(str(inputs[0])): x_n, sp.Symbol(str(inputs[1])): y_n}
y1 = y1.xreplace(sub_map)
y2 = y2.xreplace(sub_map)

# Define the symbolic function heads that KAN used
ID  = sp.Function('id')
NEG = sp.Function('-x^2')

# Collapse id(⋅) -> ⋅ and -x^2(z) -> -(z)**2
def collapse(e):
    e = e.replace(lambda z: isinstance(z, sp.FunctionClass), lambda z: z)  # no-op safety
    e = e.replace(lambda z: z.func == ID,  lambda z: z.args[0])
    e = e.replace(lambda z: z.func == NEG, lambda z: -(z.args[0])**2)
    return sp.expand(e)

y1 = collapse(y1)
y2 = collapse(y2)

# Round numeric constants to *three decimal places*
def round_numbers(expr, places=3):
    return expr.xreplace({a: round(float(a), places) for a in expr.atoms(sp.Number)})

y1 = round_numbers(y1, 3)
y2 = round_numbers(y2, 3)

# Optional: collect by x_n, y_n for readability
y1 = sp.together(sp.expand(y1))
y2 = sp.together(sp.expand(y2))

display(Math(r"\begin{cases}"
             + sp.latex(sp.Eq(sp.Symbol('x_{n+1}'), y1)) + r"\\"
             + sp.latex(sp.Eq(sp.Symbol('y_{n+1}'), y2))
             + r"\end{cases}"))

import numpy as np
import torch
import matplotlib.pyplot as plt
from kan import KAN
from matplotlib import rc
import matplotlib.gridspec as gridspec  # (not needed anymore, but ok to keep/remove)

# Set publication-quality settings
plt.rcParams.update({
    'font.size': 11,
    'font.family': 'serif',
    'font.serif': ['DejaVu Serif'],
    'mathtext.fontset': 'dejavuserif',
    'axes.labelsize': 12,
    'axes.titlesize': 13,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.dpi': 300,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'savefig.pad_inches': 0.1,
    'lines.linewidth': 1.5,
    'axes.linewidth': 1.0,
    'grid.linewidth': 0.5,
})


@torch.no_grad()
def rollout_model(model, x0, T):
    """Autoregressive rollout: x_{t+1} = model(x_t)"""
    model.eval()
    x = x0.unsqueeze(0) if x0.ndim == 1 else x0.clone()
    traj = [x.squeeze(0)]
    for _ in range(T - 1):
        x = model(x)
        traj.append(x.squeeze(0))
    return torch.stack(traj, dim=0)


def save_kan_architecture_figure(
    model,
    dataset,
    beta,
    png_path="kan_architecture.png",
    pdf_path="kan_architecture.pdf",
):
    """
    Runs a forward pass to populate activations (save_act=True),
    calls model.plot(...), and saves the resulting figure as PNG and PDF.
    """
    model.save_act = True
    with torch.no_grad():
        _ = model(dataset["test_input"])

    # model.plot usually creates/uses a Matplotlib figure internally
    model.plot(
        beta=beta,
        in_vars=[r"$x_n$", r"$y_n$"],
        out_vars=[r"$x_{n+1}$", r"$y_{n+1}$"],
    )

    fig = plt.gcf()
    # Optional: remove title here so you can add it in Inkscape, or keep it:
    # fig.suptitle("Learned KAN Architecture", fontweight="bold")

    fig.savefig(png_path, dpi=300, bbox_inches="tight", facecolor="white")
    fig.savefig(pdf_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def save_attractor_overlay_figure(
    model,
    test_seq,
    drop=200,
    png_path="henon_attractor_overlay.png",
    pdf_path="henon_attractor_overlay.pdf",
):
    """
    Rolls out the learned model from the first test point and overlays
    the true vs learned attractor, saving as PNG and PDF.
    """
    x0 = test_seq[0]
    T = int(test_seq.shape[0])

    learned_traj = rollout_model(model, x0, T).detach().cpu().numpy()
    true_traj = test_seq[:T].detach().cpu().numpy()

    true_plot = true_traj[drop:]
    learned_plot = learned_traj[drop:]

    fig, ax = plt.subplots(figsize=(6, 5))

    ax.scatter(
        true_plot[:, 0], true_plot[:, 1],
        s=1.5, alpha=0.6, c="#1f77b4",
        label="True Hénon map",
        rasterized=True,
    )
    ax.scatter(
        learned_plot[:, 0], learned_plot[:, 1],
        s=1.5, alpha=0.6, c="#ff7f0e",
        label="KAN prediction",
        rasterized=True,
    )

    ax.set_xlabel(r"$x_n$")
    ax.set_ylabel(r"$y_n$")
    # Optional: remove title and do it in Inkscape, or keep it:
    # ax.set_title("True vs. Learned Attractor", fontweight="bold")

    ax.legend(loc="upper right", framealpha=0.9, edgecolor="black")
    ax.set_aspect("equal", adjustable="box")
    ax.grid(True, alpha=0.3, linestyle="--", linewidth=0.5)
    ax.spines["top"].set_visible(True)
    ax.spines["right"].set_visible(True)

    fig.savefig(png_path, dpi=300, bbox_inches="tight", facecolor="white")
    fig.savefig(pdf_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close(fig)


# ---- Run both saves (no combined multi-panel figure) ----
print("Saving KAN architecture figure...")
save_kan_architecture_figure(
    model=model,
    dataset=dataset,
    beta=beta,
    png_path="kan_architecture.png",
    pdf_path="kan_architecture.pdf",
)

print("Saving attractor overlay figure...")
save_attractor_overlay_figure(
    model=model,
    test_seq=test_seq,
    drop=200,
    png_path="henon_attractor_overlay.png",
    pdf_path="henon_attractor_overlay.pdf",
)

print("Done!")