# -*- coding: utf-8 -*-
"""Holling_type_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/kslote1/KAN-Data-Driven-Dynamics/blob/main/Holling_type_II.ipynb
"""

!pip install pykan

# ============================================================
# Holling Type II system discovery w/ physics-informed wide features + zero-depth KAN
# - Builds a structured feature library (N,P, polynomials, Holling-II terms, combos)
# - Trains zero-depth KAN on one-step map with optional multi-step rollout loss
# - Runs auto_symbolic with complexity DOWN-WEIGHTED for physics-informed features
#   (physics features get cheaper symbolic costs; generic/poly features get pricier)
# ============================================================

import numpy as np
import torch
import matplotlib.pyplot as plt

import sympy as sp
from sympy import Eq
from sympy.printing.latex import latex
from IPython.display import display, Math

from kan import KAN

# -----------------------
# Repro / device
# -----------------------
seed = 42
rng = np.random.default_rng(seed)
torch.manual_seed(seed)
np.random.seed(seed)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

def to_tensor(a):
    return torch.tensor(a, dtype=torch.float32, device=device)

# ============================================================
# Holling Type II predator-prey ODE (Rosenzweig–MacArthur form)
#
# dN/dt = r N (1 - N/K) - (a N P) / (1 + a h N)
# dP/dt = e (a N P) / (1 + a h N) - m P
#
# N: prey, P: predator
# ============================================================

def holling_rhs(state, r, K, a, h, e, m):
    N, P = state
    # functional response denominator
    denom = 1.0 + a*h*N
    pred  = (a*N*P) / denom
    dN = r*N*(1.0 - N/K) - pred
    dP = e*pred - m*P
    return np.array([dN, dP], dtype=np.float32)

def rk4_step(state, dt, r, K, a, h, e, m):
    k1 = holling_rhs(state, r,K,a,h,e,m)
    k2 = holling_rhs(state + 0.5*dt*k1, r,K,a,h,e,m)
    k3 = holling_rhs(state + 0.5*dt*k2, r,K,a,h,e,m)
    k4 = holling_rhs(state + dt*k3, r,K,a,h,e,m)
    return (state + (dt/6.0)*(k1 + 2*k2 + 2*k3 + k4)).astype(np.float32)

def generate_holling(
    n_total=20000,
    burn_in=2000,
    dt=0.01,
    x0=(10.0, 5.0),
    params=(1.0, 50.0, 1.2, 0.1, 0.6, 0.4),
    noise_std=0.0
):
    """
    Returns a single long discrete-time series:
      series[k] ~ state at time k*dt  (after burn-in)
    """
    r, K, a, h, e, m = params
    T = n_total + burn_in
    traj = np.zeros((T, 2), dtype=np.float32)
    traj[0] = np.array(x0, dtype=np.float32)

    for i in range(T - 1):
        traj[i+1] = rk4_step(traj[i], dt, r,K,a,h,e,m)

        # optional measurement noise (keep small if you use it)
        if noise_std > 0:
            traj[i+1] += rng.normal(0.0, noise_std, size=(2,)).astype(np.float32)

        # enforce nonnegativity (common in ecology sims)
        traj[i+1] = np.maximum(traj[i+1], 0.0)

    return traj[burn_in:]

# ============================================================
# Physics-informed feature library (NumPy for dataset build)
# ============================================================

def build_holling_features_np(N, P, *, r, K, a, h, e, m):
    """
    Wide library includes:
      - generic terms: 1, N, P, N^2, P^2, N*P, ...
      - physics terms (computed using known params):
          logistic = r*N*(1 - N/K)
          denom    = 1 + a*h*N
          fN       = N/denom
          pred     = (a*N*P)/denom
          e*pred,  m*P
      - combos that align with RHS structure
    """
    one = np.ones_like(N)
    denom  = 1.0 + a*h*N
    invden = 1.0 / denom
    fN     = N * invden                # N/(1+a h N)
    pred   = (a*N*P) * invden          # a N P/(1+a h N)
    logistic = r*N*(1.0 - N/K)         # r N (1 - N/K)
    deathP   = m*P
    gainP    = e*pred

    feats = [
        one, N, P,
        N*N, P*P, N*P,
        denom, invden, fN,
        logistic, pred, gainP, deathP,
        # extra aligned combos (often helps symbolic extraction)
        r*N, (N/K), r*N*(N/K),
        a*N, a*P, (a*N*P),
        (a*h*N), (a*h*N)*P,
    ]

    names = [
        "1","N","P",
        "N^2","P^2","N*P",
        "denom","invden","fN",
        "logistic","pred","gainP","deathP",
        "r*N","N/K","r*N*(N/K)",
        "a*N","a*P","a*N*P",
        "a*h*N","(a*h*N)*P",
    ]

    Theta = np.stack(feats, axis=-1).astype(np.float32)
    return Theta, names

# ============================================================
# Physics-informed feature library (Torch for training/rollouts)
# ============================================================

def build_holling_features_torch(state_NP, *, r, K, a, h, e, m):
    # state_NP: (B,2)
    N = state_NP[:, 0]
    P = state_NP[:, 1]
    one = torch.ones_like(N)

    denom  = 1.0 + a*h*N
    invden = 1.0 / denom
    fN     = N * invden
    pred   = (a*N*P) * invden
    logistic = r*N*(1.0 - N/K)
    deathP   = m*P
    gainP    = e*pred

    feats = torch.stack([
        one, N, P,
        N*N, P*P, N*P,
        denom, invden, fN,
        logistic, pred, gainP, deathP,
        r*N, (N/K), r*N*(N/K),
        a*N, a*P, (a*N*P),
        (a*h*N), (a*h*N)*P,
    ], dim=1)
    return feats  # (B,F)

# ============================================================
# Generate data (discrete-time sequence from ODE integrator)
# ============================================================

# "True" params for data generation (edit freely)
r_true = 1.0
K_true = 50.0
a_true = 1.2
h_true = 0.1
e_true = 0.6
m_true = 0.4

dt = 0.02
n_samples = 20000
burn_in = 2000

series = generate_holling(
    n_total=n_samples,
    burn_in=burn_in,
    dt=dt,
    x0=(10.0, 5.0),
    params=(r_true, K_true, a_true, h_true, e_true, m_true),
    noise_std=0.0
)

X_state = series[:-1]   # (N,2)
Y_state = series[1:]    # (N,2)

Theta_np, feat_names = build_holling_features_np(
    X_state[:, 0], X_state[:, 1],
    r=r_true, K=K_true, a=a_true, h=h_true, e=e_true, m=m_true
)

print("Feature count:", Theta_np.shape[1])
print("First 10 features:", feat_names[:10])

# ============================================================
# Temporal split (train/val/test)
# ============================================================
test_frac = 0.2
val_frac  = 0.2

N = len(Theta_np)
n_test = int(N * test_frac)
n_val  = int((N - n_test) * val_frac)

Theta_train = Theta_np[:N - n_test - n_val]
Y_train     = Y_state[:N - n_test - n_val]

Theta_val = Theta_np[N - n_test - n_val : N - n_test]
Y_val     = Y_state[N - n_test - n_val : N - n_test]

Theta_test = Theta_np[N - n_test :]
Y_test     = Y_state[N - n_test :]

Theta_train_t = to_tensor(Theta_train)
Y_train_t     = to_tensor(Y_train)
Theta_val_t   = to_tensor(Theta_val)
Y_val_t       = to_tensor(Y_val)
Theta_test_t  = to_tensor(Theta_test)
Y_test_t      = to_tensor(Y_test)

X_state_train = to_tensor(X_state[:N - n_test - n_val])
X_state_test  = to_tensor(X_state[N - n_test :])

# ============================================================
# Normalize features (strongly recommended with ratio terms)
# ============================================================
X_mean = Theta_train_t.mean(dim=0, keepdim=True)
X_std  = Theta_train_t.std(dim=0, keepdim=True) + 1e-8

def normalize_feats(Theta_t):
    return (Theta_t - X_mean) / X_std

Theta_train_n = normalize_feats(Theta_train_t)
Theta_val_n   = normalize_feats(Theta_val_t)
Theta_test_n  = normalize_feats(Theta_test_t)

dataset = {
    "train_input": Theta_train_n,
    "train_label": Y_train_t,
    "test_input":  Theta_test_n,
    "test_label":  Y_test_t,
}

# ============================================================
# Model: zero-depth KAN learns discrete map Theta(N,P) -> (N_next, P_next)
# ============================================================
F = Theta_train_n.shape[1]
model = KAN(width=[F, 2], grid=5, k=3, base_fun='zero', seed=seed).to(device)

# ============================================================
# Custom training loop (one-step + rollout loss)
# ============================================================

def map_fn_from_state(state_NP):
    Theta = build_holling_features_torch(
        state_NP, r=r_true, K=K_true, a=a_true, h=h_true, e=e_true, m=m_true
    )
    Theta_n = (Theta - X_mean) / X_std
    return model(Theta_n)  # (B,2)

def rollout_loss(seq_states, horizon=25, n_starts=512):
    """
    seq_states: (T,2) contiguous trajectory
    """
    T = seq_states.shape[0]
    if T <= horizon + 1:
        return torch.tensor(0.0, device=device)

    idx0 = torch.randint(0, T - horizon - 1, (n_starts,), device=device)
    s = seq_states[idx0]

    loss = 0.0
    for k in range(1, horizon + 1):
        s = map_fn_from_state(s)
        s_true = seq_states[idx0 + k]
        loss = loss + torch.mean((s - s_true) ** 2)
    return loss / horizon

# training hyperparams
steps = 2500
lr = 2e-3
batch_size = 4096

rollout_weight  = 0.6     # set 0 to disable
rollout_horizon = 25
rollout_starts  = 512

opt = torch.optim.Adam(model.parameters(), lr=lr)

train_traj = to_tensor(series[: (N - n_test - n_val) + 1])  # (T_train,2)

best_val = float("inf")
best_state = None

for it in range(1, steps + 1):
    model.train()

    idx = torch.randint(0, Theta_train_n.shape[0], (batch_size,), device=device)
    pred_next = model(Theta_train_n[idx])
    loss_1 = torch.mean((pred_next - Y_train_t[idx]) ** 2)

    loss_r = rollout_loss(train_traj, horizon=rollout_horizon, n_starts=rollout_starts) if rollout_weight > 0 else 0.0
    loss = (1.0 - rollout_weight) * loss_1 + rollout_weight * loss_r

    opt.zero_grad(set_to_none=True)
    loss.backward()
    opt.step()

    if it % 100 == 0 or it == 1:
        model.eval()
        with torch.no_grad():
            val_pred = model(Theta_val_n)
            val_mse = torch.mean((val_pred - Y_val_t) ** 2).item()

        if val_mse < best_val:
            best_val = val_mse
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        print(f"step {it:5d} | loss={loss.item():.3e} | one-step={loss_1.item():.3e} | rollout={float(loss_r):.3e} | val_mse={val_mse:.3e}")

if best_state is not None:
    model.load_state_dict({k: v.to(device) for k, v in best_state.items()})
print("Best val mse:", best_val)

# ============================================================
# Sanity check: one-step + rollout on test
# ============================================================
model.eval()
with torch.no_grad():
    test_pred = model(Theta_test_n)
    test_mse = torch.mean((test_pred - Y_test_t) ** 2).item()
print("Test one-step MSE:", test_mse)

def rollout_eval(seq_states, horizon=600):
    s = seq_states[0:1]
    preds = [s]
    for _ in range(horizon):
        s = map_fn_from_state(s)
        preds.append(s)
    preds = torch.cat(preds, dim=0)
    truth = seq_states[:horizon+1]
    return preds, truth

test_traj = to_tensor(series[N - n_test : N - n_test + 5000])
with torch.no_grad():
    pred_roll, true_roll = rollout_eval(test_traj, horizon=800)
    roll_mse = torch.mean((pred_roll - true_roll) ** 2).item()
print("Test rollout MSE:", roll_mse)

pred_np = pred_roll.detach().cpu().numpy()
true_np = true_roll.detach().cpu().numpy()

plt.figure()
plt.plot(true_np[:,0], label="true N")
plt.plot(pred_np[:,0], label="pred N", alpha=0.8)
plt.legend()
plt.title("Holling-II rollout: prey time series")
plt.show()

plt.figure()
plt.plot(true_np[:,1], label="true P")
plt.plot(pred_np[:,1], label="pred P", alpha=0.8)
plt.legend()
plt.title("Holling-II rollout: predator time series")
plt.show()

plt.figure()
plt.plot(true_np[:,0], true_np[:,1], label="true")
plt.plot(pred_np[:,0], pred_np[:,1], label="pred", alpha=0.8)
plt.legend()
plt.title("Holling-II rollout (phase portrait)")
plt.show()

# ============================================================
# Symbolic extraction with PHYSICS-FEATURE complexity down-weighting
#
# Key idea:
#   - physics-informed features get LOWER cost library (PHYS_SYMBOLIC_LIB)
#   - generic features get HIGHER cost library (GEN_SYMBOLIC_LIB)
# so the solver prefers physics features when fit is comparable.
# ============================================================

model.save_act = True
_ = model(Theta_train_n[:2048])

# Basic building blocks (you can expand this if you like)
PHYS_SYMBOLIC_LIB = {
    'x':   (lambda x: x,    lambda x: x,          1, lambda x, y_th: ((), x)),
    'x^2': (lambda x: x**2, lambda x: x**2,       2, lambda x, y_th: ((), x**2)),
    'x^3': (lambda x: x**3, lambda x: x**3,       3, lambda x, y_th: ((), x**3)),
    '0':   (lambda x: x*0,  lambda x: x*0,        0, lambda x, y_th: ((), x*0)),
}

# Make "generic" expressions more expensive (discourages them)
GEN_SYMBOLIC_LIB = {
    'x':   (lambda x: x,    lambda x: x,          3, lambda x, y_th: ((), x)),
    'x^2': (lambda x: x**2, lambda x: x**2,       4, lambda x, y_th: ((), x**2)),
    'x^3': (lambda x: x**3, lambda x: x**3,       5, lambda x, y_th: ((), x**3)),
    '0':   (lambda x: x*0,  lambda x: x*0,        0, lambda x, y_th: ((), x*0)),
}

# Which feature indices are "physics-informed" (cheap)?
# Using the names list above:
# indices:
#  0  1  2  3  4  5  6     7      8     9         10    11     12     ...
#  1, N, P, N^2,P^2,N*P, denom, invden, fN, logistic, pred, gainP, deathP, ...
#
# I'd treat the core RHS-aligned terms as "physics":
physics_idx = set([
    feat_names.index("denom"),
    feat_names.index("invden"),
    feat_names.index("fN"),
    feat_names.index("logistic"),
    feat_names.index("pred"),
    feat_names.index("gainP"),
    feat_names.index("deathP"),
])

def auto_symbolic_physics_preferred(
    self,
    a_range=(-10, 10),
    b_range=(-10, 10),
    weight_simple=0.8,
    r2_threshold=0.90,
    verbose=1
):
    """
    Same spirit as your Ikeda auto_symbolic_complexity_aware, but:
      - PHYS features use PHYS_SYMBOLIC_LIB (cheaper)
      - others use GEN_SYMBOLIC_LIB (more expensive)
    """
    for l in range(len(self.width_in) - 1):
        for i in range(self.width_in[l]):
            for j in range(self.width_out[l + 1]):

                lib = PHYS_SYMBOLIC_LIB if i in physics_idx else GEN_SYMBOLIC_LIB
                name, fun, r2, c = self.suggest_symbolic(
                    l, i, j,
                    a_range=a_range, b_range=b_range,
                    lib=lib,
                    verbose=False,
                    weight_simple=weight_simple
                )

                if r2 >= r2_threshold:
                    self.fix_symbolic(l, i, j, name, verbose=verbose > 1, log_history=False)
                    if verbose >= 1:
                        tag = "PHYS" if (i in physics_idx) else "GEN"
                        print(f'fixing ({l},{i},{j}) [{tag}] with {name}, r2={r2:.4f}, c={c}')
                else:
                    self.fix_symbolic(l, i, j, '0', verbose=verbose > 1, log_history=False)
                    if verbose >= 1:
                        print(f'omit ({l},{i},{j}) best={name}, r2={r2:.4f} < {r2_threshold}, set to 0')

    self.log_history('auto_symbolic_physics_preferred')

# Run symbolic fitting
auto_symbolic_physics_preferred(model, weight_simple=0.7, r2_threshold=0.90, verbose=1)

# ============================================================
# Extract expressions and substitute semantic meanings of inputs
# ============================================================

exprs_raw, vars_ = model.symbolic_formula()
n_in = int(model.width_in[0])
if len(vars_) < n_in:
    raise ValueError(f"symbolic_formula returned only {len(vars_)} vars, but model has n_in={n_in}")

# SymPy symbols for state + params
Nsym, Psym = sp.symbols("N P", real=True, nonnegative=True)
r, K, a, h, e, m = sp.symbols("r K a h e m", real=True)

denom  = 1 + a*h*Nsym
invden = 1/denom
fN     = Nsym*invden
pred   = (a*Nsym*Psym)*invden
logistic = r*Nsym*(1 - Nsym/K)
deathP = m*Psym
gainP  = e*pred

# Match feature_syms order exactly to build_holling_features_* order
feature_syms = [
    sp.Integer(1), Nsym, Psym,
    Nsym**2, Psym**2, Nsym*Psym,
    denom, invden, fN,
    logistic, pred, gainP, deathP,
    r*Nsym, (Nsym/K), r*Nsym*(Nsym/K),
    a*Nsym, a*Psym, a*Nsym*Psym,
    a*h*Nsym, (a*h*Nsym)*Psym,
]

sub_map = {vars_[i]: feature_syms[i] for i in range(n_in)}

def round_numbers(expr, places=4):
    repl = {}
    for aa in expr.atoms(sp.Number):
        try:
            repl[aa] = sp.Float(round(float(aa), places))
        except Exception:
            pass
    return expr.xreplace(repl)

def flatten(obj):
    if isinstance(obj, (list, tuple)):
        out = []
        for it in obj:
            out.extend(flatten(it))
        return out
    return [obj]

exprs_list = flatten(exprs_raw)

cleaned = []
for expr in exprs_list:
    if not hasattr(expr, "free_symbols"):
        continue
    ex = expr.subs(sub_map)
    ex = sp.together(sp.expand(ex))
    ex = round_numbers(ex, 4)
    cleaned.append(ex)

# Display discovered discrete-time map equations
N_next, P_next = sp.symbols("N_{n+1} P_{n+1}")
if len(cleaned) >= 2:
    display(Math(latex(Eq(N_next, cleaned[0]))))
    display(Math(latex(Eq(P_next, cleaned[1]))))
else:
    for k, ex in enumerate(cleaned):
        display(Math(latex(Eq(sp.Symbol(f"out_{k}"), ex))))

print("\nTrue continuous-time Holling-II RHS (Rosenzweig–MacArthur):")
print("dN/dt = r N (1 - N/K) - (a N P)/(1 + a h N)")
print("dP/dt = e (a N P)/(1 + a h N) - m P")
print("\nDiscrete-time training target is one-step flow map with dt =", dt)

for i, nm in enumerate(feat_names):
    print(i, nm, " <-> ", feature_syms[i])

model.unfix_symbolic_all()
# Run symbolic fitting
auto_symbolic_physics_preferred(model, weight_simple=0.1, r2_threshold=0.90, verbose=1)

# ============================================================
# Extract expressions and substitute semantic meanings of inputs
# ============================================================

exprs_raw, vars_ = model.symbolic_formula()
n_in = int(model.width_in[0])
if len(vars_) < n_in:
    raise ValueError(f"symbolic_formula returned only {len(vars_)} vars, but model has n_in={n_in}")

# SymPy symbols for state + params
Nsym, Psym = sp.symbols("N P", real=True, nonnegative=True)
r, K, a, h, e, m = sp.symbols("r K a h e m", real=True)

denom  = 1 + a*h*Nsym
invden = 1/denom
fN     = Nsym*invden
pred   = (a*Nsym*Psym)*invden
logistic = r*Nsym*(1 - Nsym/K)
deathP = m*Psym
gainP  = e*pred

# Match feature_syms order exactly to build_holling_features_* order
feature_syms = [
    sp.Integer(1), Nsym, Psym,
    Nsym**2, Psym**2, Nsym*Psym,
    denom, invden, fN,
    logistic, pred, gainP, deathP,
    r*Nsym, (Nsym/K), r*Nsym*(Nsym/K),
    a*Nsym, a*Psym, a*Nsym*Psym,
    a*h*Nsym, (a*h*Nsym)*Psym,
]

sub_map = {vars_[i]: feature_syms[i] for i in range(n_in)}

def round_numbers(expr, places=4):
    repl = {}
    for aa in expr.atoms(sp.Number):
        try:
            repl[aa] = sp.Float(round(float(aa), places))
        except Exception:
            pass
    return expr.xreplace(repl)

def flatten(obj):
    if isinstance(obj, (list, tuple)):
        out = []
        for it in obj:
            out.extend(flatten(it))
        return out
    return [obj]

exprs_list = flatten(exprs_raw)

cleaned = []
for expr in exprs_list:
    if not hasattr(expr, "free_symbols"):
        continue
    ex = expr.subs(sub_map)
    ex = sp.together(sp.expand(ex))
    ex = round_numbers(ex, 4)
    cleaned.append(ex)

# Display discovered discrete-time map equations
N_next, P_next = sp.symbols("N_{n+1} P_{n+1}")
if len(cleaned) >= 2:
    display(Math(latex(Eq(N_next, cleaned[0]))))
    display(Math(latex(Eq(P_next, cleaned[1]))))
else:
    for k, ex in enumerate(cleaned):
        display(Math(latex(Eq(sp.Symbol(f"out_{k}"), ex))))

print("\nTrue continuous-time Holling-II RHS (Rosenzweig–MacArthur):")
print("dN/dt = r N (1 - N/K) - (a N P)/(1 + a h N)")
print("dP/dt = e (a N P)/(1 + a h N) - m P")
print("\nDiscrete-time training target is one-step flow map with dt =", dt)

model.eval()
with torch.no_grad():
    P0 = torch.tensor([[5.0]], device=device)
    Ns = torch.linspace(1.0, 40.0, 200, device=device).unsqueeze(1)
    states = torch.cat([Ns, P0.repeat(Ns.shape[0],1)], dim=1)
    out = map_fn_from_state(states)  # predicted (N_next, P_next)
    print("var(N_next) over N:", out[:,0].var().item())
    print("var(P_next) over N:", out[:,1].var().item())

param_subs = {
    r: r_true, K: K_true, a: a_true, h: h_true, e: e_true, m: m_true
}
print(sp.simplify(cleaned[0].subs(param_subs)))
print(sp.simplify(cleaned[1].subs(param_subs)))

# ============================================================
# Holling Type II discovery w/ physics-informed wide features + zero-depth KAN
# TRAINING ON DERIVATIVES (RHS) INSTEAD OF ONE-STEP MAP
# - Simulate trajectories (RK4) to get state samples
# - Labels are true derivatives from the Holling-II RHS at those states
# - Train KAN: Theta(N,P) -> (dN/dt, dP/dt)
# - Optional multi-step rollout loss via Euler (or RK4) integrating predicted derivatives
# - Symbolic extraction w/ complexity DOWN-WEIGHTED for physics-informed features
# ============================================================

import numpy as np
import torch
import matplotlib.pyplot as plt

import sympy as sp
from sympy import Eq
from sympy.printing.latex import latex
from IPython.display import display, Math

from kan import KAN

# -----------------------
# Repro / device
# -----------------------
seed = 42
rng = np.random.default_rng(seed)
torch.manual_seed(seed)
np.random.seed(seed)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

def to_tensor(a):
    return torch.tensor(a, dtype=torch.float32, device=device)

# ============================================================
# Holling Type II predator-prey ODE (Rosenzweig–MacArthur)
# dN/dt = r N (1 - N/K) - (a N P)/(1 + a h N)
# dP/dt = e (a N P)/(1 + a h N) - m P
# ============================================================

def holling_rhs_np(state, r, K, a, h, e, m):
    N, P = state
    denom = 1.0 + a*h*N
    pred  = (a*N*P) / denom
    dN = r*N*(1.0 - N/K) - pred
    dP = e*pred - m*P
    return np.array([dN, dP], dtype=np.float32)

def rk4_step_np(state, dt, r, K, a, h, e, m):
    k1 = holling_rhs_np(state, r,K,a,h,e,m)
    k2 = holling_rhs_np(state + 0.5*dt*k1, r,K,a,h,e,m)
    k3 = holling_rhs_np(state + 0.5*dt*k2, r,K,a,h,e,m)
    k4 = holling_rhs_np(state + dt*k3, r,K,a,h,e,m)
    return (state + (dt/6.0)*(k1 + 2*k2 + 2*k3 + k4)).astype(np.float32)

def generate_holling_traj_np(
    n_total=3000,
    burn_in=200,
    dt=0.02,
    x0=(10.0, 5.0),
    params=(1.0, 50.0, 1.2, 0.1, 0.6, 0.4),
    noise_std=0.0
):
    r, K, a, h, e, m = params
    T = n_total + burn_in
    traj = np.zeros((T, 2), dtype=np.float32)
    traj[0] = np.array(x0, dtype=np.float32)

    for i in range(T - 1):
        traj[i+1] = rk4_step_np(traj[i], dt, r,K,a,h,e,m)
        if noise_std > 0:
            traj[i+1] += rng.normal(0.0, noise_std, size=(2,)).astype(np.float32)
        traj[i+1] = np.maximum(traj[i+1], 0.0)
    return traj[burn_in:]

# ============================================================
# Physics-informed feature library (NumPy)
# ============================================================

def build_holling_features_np(N, P, *, r, K, a, h, e, m):
    one = np.ones_like(N)

    denom  = 1.0 + a*h*N
    invden = 1.0 / denom
    fN     = N * invden
    pred   = (a*N*P) * invden
    logistic = r*N*(1.0 - N/K)
    deathP   = m*P
    gainP    = e*pred

    feats = [
        one, N, P,
        N*N, P*P, N*P,
        denom, invden, fN,
        logistic, pred, gainP, deathP,
        # optional aligned combos
        r*N, (N/K), r*N*(N/K),
        a*N, a*P, (a*N*P),
        (a*h*N), (a*h*N)*P,
    ]

    names = [
        "1","N","P",
        "N^2","P^2","N*P",
        "denom","invden","fN",
        "logistic","pred","gainP","deathP",
        "r*N","N/K","r*N*(N/K)",
        "a*N","a*P","a*N*P",
        "a*h*N","(a*h*N)*P",
    ]
    Theta = np.stack(feats, axis=-1).astype(np.float32)
    return Theta, names

# ============================================================
# Physics-informed feature library (Torch)
# ============================================================

def build_holling_features_torch(state_NP, *, r, K, a, h, e, m):
    N = state_NP[:, 0]
    P = state_NP[:, 1]
    one = torch.ones_like(N)

    denom  = 1.0 + a*h*N
    invden = 1.0 / denom
    fN     = N * invden
    pred   = (a*N*P) * invden
    logistic = r*N*(1.0 - N/K)
    deathP   = m*P
    gainP    = e*pred

    feats = torch.stack([
        one, N, P,
        N*N, P*P, N*P,
        denom, invden, fN,
        logistic, pred, gainP, deathP,
        r*N, (N/K), r*N*(N/K),
        a*N, a*P, (a*N*P),
        (a*h*N), (a*h*N)*P,
    ], dim=1)
    return feats  # (B,F)

# ============================================================
# Build multi-trajectory dataset (recommended)
# ============================================================

# "True" parameters (used for data + physics features)
r_true = 1.0
K_true = 50.0
a_true = 1.2
h_true = 0.1
e_true = 0.6
m_true = 0.4

dt = 0.02

def make_dataset_multi_ic_rhs(
    M=50, n_total=3000, burn_in=200, dt=0.02,
    N_range=(1.0, 60.0), P_range=(0.5, 30.0),
    params=(r_true, K_true, a_true, h_true, e_true, m_true),
    noise_std=0.0,
):
    r_,K_,a_,h_,e_,m_ = params
    X_list, dX_list, traj_list = [], [], []

    for _ in range(M):
        N0 = rng.uniform(*N_range)
        P0 = rng.uniform(*P_range)
        traj = generate_holling_traj_np(
            n_total=n_total, burn_in=burn_in, dt=dt,
            x0=(N0, P0),
            params=(r_,K_,a_,h_,e_,m_),
            noise_std=noise_std
        )
        # states
        X = traj[:-1].astype(np.float32)
        # true derivatives at those states
        dX = np.stack([holling_rhs_np(s, r_,K_,a_,h_,e_,m_) for s in X], axis=0).astype(np.float32)

        X_list.append(X)
        dX_list.append(dX)
        traj_list.append(traj.astype(np.float32))

    X_state = np.concatenate(X_list, axis=0)
    dXdt    = np.concatenate(dX_list, axis=0)
    # Keep trajectories for rollout eval/loss if desired
    return X_state, dXdt, traj_list

X_state, dXdt, traj_list = make_dataset_multi_ic_rhs(
    M=50, n_total=3000, burn_in=200, dt=dt,
    N_range=(1.0, 60.0), P_range=(0.5, 30.0),
    noise_std=0.0
)

Theta_np, feat_names = build_holling_features_np(
    X_state[:,0], X_state[:,1],
    r=r_true, K=K_true, a=a_true, h=h_true, e=e_true, m=m_true
)

print("Samples:", X_state.shape[0], " | Feature count:", Theta_np.shape[1])
print("First 10 features:", feat_names[:10])

# ============================================================
# Random split (not temporal now; data are pooled from multiple ICs)
# ============================================================

N = Theta_np.shape[0]
idx_all = np.arange(N)
rng.shuffle(idx_all)

test_frac = 0.2
val_frac  = 0.2
n_test = int(N * test_frac)
n_val  = int((N - n_test) * val_frac)

idx_test = idx_all[:n_test]
idx_val  = idx_all[n_test:n_test+n_val]
idx_train= idx_all[n_test+n_val:]

Theta_train = Theta_np[idx_train]
Y_train     = dXdt[idx_train]

Theta_val = Theta_np[idx_val]
Y_val     = dXdt[idx_val]

Theta_test = Theta_np[idx_test]
Y_test     = dXdt[idx_test]

Theta_train_t = to_tensor(Theta_train)
Y_train_t     = to_tensor(Y_train)
Theta_val_t   = to_tensor(Theta_val)
Y_val_t       = to_tensor(Y_val)
Theta_test_t  = to_tensor(Theta_test)
Y_test_t      = to_tensor(Y_test)

X_state_train = to_tensor(X_state[idx_train])
X_state_val   = to_tensor(X_state[idx_val])
X_state_test  = to_tensor(X_state[idx_test])

# ============================================================
# Normalize features
# ============================================================

X_mean = Theta_train_t.mean(dim=0, keepdim=True)
X_std  = Theta_train_t.std(dim=0, keepdim=True) + 1e-8

def normalize_feats(Theta_t):
    return (Theta_t - X_mean) / X_std

Theta_train_n = normalize_feats(Theta_train_t)
Theta_val_n   = normalize_feats(Theta_val_t)
Theta_test_n  = normalize_feats(Theta_test_t)

# ============================================================
# Model: zero-depth KAN learns RHS: Theta(N,P) -> (dN/dt, dP/dt)
# ============================================================

F = Theta_train_n.shape[1]
model = KAN(width=[F, 2], grid=5, k=3, base_fun='zero', seed=seed).to(device)

def rhs_fn_from_state(state_NP):
    Theta = build_holling_features_torch(
        state_NP, r=r_true, K=K_true, a=a_true, h=h_true, e=e_true, m=m_true
    )
    Theta_n = (Theta - X_mean) / X_std
    return model(Theta_n)  # (B,2) derivative prediction

# ============================================================
# Optional rollout loss: integrate predicted RHS forward
# (Euler shown; you can swap to RK4 in torch if you want)
# ============================================================

def rollout_loss_rhs(traj, horizon=50, n_starts=256, dt=0.02):
    """
    traj: (T,2) torch trajectory from simulator
    Roll forward using predicted RHS + Euler:
      s_{k+1} = s_k + dt * f_theta(s_k)
    Compare to true states along the trajectory.
    """
    T = traj.shape[0]
    if T <= horizon + 1:
        return torch.tensor(0.0, device=device)

    idx0 = torch.randint(0, T - horizon - 1, (n_starts,), device=device)
    s = traj[idx0]  # (B,2)
    loss = 0.0
    for k in range(1, horizon + 1):
        ds = rhs_fn_from_state(s)
        s  = s + dt * ds
        s  = torch.clamp(s, min=0.0)  # keep nonnegative
        s_true = traj[idx0 + k]
        loss = loss + torch.mean((s - s_true) ** 2)
    return loss / horizon

# Use one or more simulator trajectories for rollout loss
train_roll_traj = to_tensor(traj_list[0])  # pick one; you can cycle or concatenate if desired

# ============================================================
# Training loop
# ============================================================

steps = 3000
lr = 2e-3
batch_size = 4096

rollout_weight  = 0.3     # set 0 to disable
rollout_horizon = 60
rollout_starts  = 512

opt = torch.optim.Adam(model.parameters(), lr=lr)

best_val = float("inf")
best_state = None

for it in range(1, steps + 1):
    model.train()

    idx = torch.randint(0, Theta_train_n.shape[0], (batch_size,), device=device)
    pred = model(Theta_train_n[idx])              # predicted derivatives
    loss_1 = torch.mean((pred - Y_train_t[idx])**2)

    loss_r = rollout_loss_rhs(
        train_roll_traj, horizon=rollout_horizon, n_starts=rollout_starts, dt=dt
    ) if rollout_weight > 0 else 0.0

    loss = (1.0 - rollout_weight) * loss_1 + rollout_weight * loss_r

    opt.zero_grad(set_to_none=True)
    loss.backward()
    opt.step()

    if it % 100 == 0 or it == 1:
        model.eval()
        with torch.no_grad():
            val_pred = model(Theta_val_n)
            val_mse = torch.mean((val_pred - Y_val_t)**2).item()
        if val_mse < best_val:
            best_val = val_mse
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        print(f"step {it:5d} | loss={loss.item():.3e} | rhs_mse={loss_1.item():.3e} | roll={float(loss_r):.3e} | val_mse={val_mse:.3e}")

if best_state is not None:
    model.load_state_dict({k: v.to(device) for k, v in best_state.items()})
print("Best val mse:", best_val)

# ============================================================
# Test metrics (RHS prediction)
# ============================================================

model.eval()
with torch.no_grad():
    test_pred = model(Theta_test_n)
    test_mse = torch.mean((test_pred - Y_test_t)**2).item()
print("Test RHS MSE:", test_mse)

# Sensitivity sanity check: does predicted RHS depend on both N and P?
with torch.no_grad():
    P0 = torch.tensor([[5.0]], device=device)
    Ns = torch.linspace(1.0, 40.0, 200, device=device).unsqueeze(1)
    states = torch.cat([Ns, P0.repeat(Ns.shape[0],1)], dim=1)
    out = rhs_fn_from_state(states)
    print("var(dN/dt) over N (P fixed):", out[:,0].var().item())
    print("var(dP/dt) over N (P fixed):", out[:,1].var().item())

# ============================================================
# Rollout eval (integrate predicted RHS) on a fresh simulator trajectory
# ============================================================

def rollout_eval_rhs(traj, horizon=800, dt=0.02):
    """
    traj: (T,2) torch truth trajectory
    Start from traj[0], integrate predicted RHS forward, compare
    """
    s = traj[0:1]  # (1,2)
    preds = [s]
    for _ in range(horizon):
        ds = rhs_fn_from_state(s)
        s = s + dt * ds
        s = torch.clamp(s, min=0.0)
        preds.append(s)
    preds = torch.cat(preds, dim=0)
    truth = traj[:horizon+1]
    return preds, truth

test_traj = to_tensor(traj_list[-1])  # another trajectory
with torch.no_grad():
    pred_roll, true_roll = rollout_eval_rhs(test_traj, horizon=800, dt=dt)
    roll_mse = torch.mean((pred_roll - true_roll)**2).item()
print("Rollout MSE (state space):", roll_mse)

pred_np = pred_roll.detach().cpu().numpy()
true_np = true_roll.detach().cpu().numpy()

plt.figure()
plt.plot(true_np[:,0], label="true N")
plt.plot(pred_np[:,0], label="pred N", alpha=0.8)
plt.legend()
plt.title("Holling-II rollout from learned RHS: prey")
plt.show()

plt.figure()
plt.plot(true_np[:,1], label="true P")
plt.plot(pred_np[:,1], label="pred P", alpha=0.8)
plt.legend()
plt.title("Holling-II rollout from learned RHS: predator")
plt.show()

plt.figure()
plt.plot(true_np[:,0], true_np[:,1], label="true")
plt.plot(pred_np[:,0], pred_np[:,1], label="pred", alpha=0.8)
plt.legend()
plt.title("Holling-II phase portrait rollout (learned RHS)")
plt.show()

# ============================================================
# Symbolic extraction w/ physics features down-weighted (preferred)
# ============================================================

model.save_act = True
_ = model(Theta_train_n[:2048])

PHYS_SYMBOLIC_LIB = {
    'x':   (lambda x: x,    lambda x: x,          1, lambda x, y_th: ((), x)),
    'x^2': (lambda x: x**2, lambda x: x**2,       2, lambda x, y_th: ((), x**2)),
    'x^3': (lambda x: x**3, lambda x: x**3,       3, lambda x, y_th: ((), x**3)),
    '0':   (lambda x: x*0,  lambda x: x*0,        0, lambda x, y_th: ((), x*0)),
}

GEN_SYMBOLIC_LIB = {
    'x':   (lambda x: x,    lambda x: x,          3, lambda x, y_th: ((), x)),
    'x^2': (lambda x: x**2, lambda x: x**2,       4, lambda x, y_th: ((), x**2)),
    'x^3': (lambda x: x**3, lambda x: x**3,       5, lambda x, y_th: ((), x**3)),
    '0':   (lambda x: x*0,  lambda x: x*0,        0, lambda x, y_th: ((), x*0)),
}

physics_idx = set([
    feat_names.index("denom"),
    feat_names.index("invden"),
    feat_names.index("fN"),
    feat_names.index("logistic"),
    feat_names.index("pred"),
    feat_names.index("gainP"),
    feat_names.index("deathP"),
])

def auto_symbolic_physics_preferred(
    self,
    a_range=(-10, 10),
    b_range=(-10, 10),
    weight_simple=0.8,
    r2_threshold=0.90,
    verbose=1
):
    for l in range(len(self.width_in) - 1):
        for i in range(self.width_in[l]):
            for j in range(self.width_out[l + 1]):
                lib = PHYS_SYMBOLIC_LIB if i in physics_idx else GEN_SYMBOLIC_LIB
                name, fun, r2, c = self.suggest_symbolic(
                    l, i, j,
                    a_range=a_range, b_range=b_range,
                    lib=lib,
                    verbose=False,
                    weight_simple=weight_simple
                )
                if r2 >= r2_threshold:
                    self.fix_symbolic(l, i, j, name, verbose=verbose > 1, log_history=False)
                    if verbose >= 1:
                        tag = "PHYS" if (i in physics_idx) else "GEN"
                        print(f'fixing ({l},{i},{j}) [{tag}] with {name}, r2={r2:.4f}, c={c}')
                else:
                    self.fix_symbolic(l, i, j, '0', verbose=verbose > 1, log_history=False)
                    if verbose >= 1:
                        print(f'omit ({l},{i},{j}) best={name}, r2={r2:.4f} < {r2_threshold}, set to 0')
    self.log_history('auto_symbolic_physics_preferred')

auto_symbolic_physics_preferred(model, weight_simple=0.7, r2_threshold=0.90, verbose=1)

# ============================================================
# Extract symbolic RHS and substitute semantic meanings of inputs
# IMPORTANT: symbolic_formula uses normalized inputs -> substitute normalized feature symbols
# ============================================================

exprs_raw, vars_ = model.symbolic_formula()
n_in = int(model.width_in[0])
if len(vars_) < n_in:
    raise ValueError(f"symbolic_formula returned only {len(vars_)} vars, but model has n_in={n_in}")

# SymPy state + params
Nsym, Psym = sp.symbols("N P", real=True, nonnegative=True)
r, K, a, h, e, m = sp.symbols("r K a h e m", real=True)

denom  = 1 + a*h*Nsym
invden = 1/denom
fN     = Nsym*invden
pred   = (a*Nsym*Psym)*invden
logistic = r*Nsym*(1 - Nsym/K)
deathP = m*Psym
gainP  = e*pred

feature_syms = [
    sp.Integer(1), Nsym, Psym,
    Nsym**2, Psym**2, Nsym*Psym,
    denom, invden, fN,
    logistic, pred, gainP, deathP,
    r*Nsym, (Nsym/K), r*Nsym*(Nsym/K),
    a*Nsym, a*Psym, a*Nsym*Psym,
    a*h*Nsym, (a*h*Nsym)*Psym,
]

# Normalization-aware substitution: vars_i -> (Theta_i - mu_i)/sd_i
mu = X_mean.detach().cpu().numpy().reshape(-1)
sd = X_std.detach().cpu().numpy().reshape(-1)
feature_syms_norm = [(feature_syms[i] - sp.Float(mu[i])) / sp.Float(sd[i]) for i in range(n_in)]
sub_map = {vars_[i]: feature_syms_norm[i] for i in range(n_in)}

def round_numbers(expr, places=5):
    repl = {}
    for aa in expr.atoms(sp.Number):
        try:
            repl[aa] = sp.Float(round(float(aa), places))
        except Exception:
            pass
    return expr.xreplace(repl)

def flatten(obj):
    if isinstance(obj, (list, tuple)):
        out = []
        for it in obj:
            out.extend(flatten(it))
        return out
    return [obj]

exprs_list = flatten(exprs_raw)

cleaned = []
for expr in exprs_list:
    if not hasattr(expr, "free_symbols"):
        continue
    ex = expr.subs(sub_map)
    ex = sp.together(sp.expand(ex))
    ex = round_numbers(ex, 5)
    cleaned.append(ex)

# Display discovered RHS equations (dN/dt, dP/dt)
dNdt, dPdt = sp.symbols(r"\dot{N} \dot{P}")
if len(cleaned) >= 2:
    display(Math(latex(Eq(dNdt, cleaned[0]))))
    display(Math(latex(Eq(dPdt, cleaned[1]))))
else:
    for k, ex in enumerate(cleaned):
        display(Math(latex(Eq(sp.Symbol(f"out_{k}"), ex))))

print("\nTrue Holling-II RHS:")
print("dN/dt = r N (1 - N/K) - (a N P)/(1 + a h N)")
print("dP/dt = e (a N P)/(1 + a h N) - m P")
print("dt used for rollouts =", dt)

auto_symbolic_physics_preferred(model, weight_simple=0.0, r2_threshold=0.90, verbose=1)

# ============================================================
# Extract symbolic RHS and substitute semantic meanings of inputs
# IMPORTANT: symbolic_formula uses normalized inputs -> substitute normalized feature symbols
# ============================================================

exprs_raw, vars_ = model.symbolic_formula()
n_in = int(model.width_in[0])
if len(vars_) < n_in:
    raise ValueError(f"symbolic_formula returned only {len(vars_)} vars, but model has n_in={n_in}")

# SymPy state + params
Nsym, Psym = sp.symbols("N P", real=True, nonnegative=True)
r, K, a, h, e, m = sp.symbols("r K a h e m", real=True)

denom  = 1 + a*h*Nsym
invden = 1/denom
fN     = Nsym*invden
pred   = (a*Nsym*Psym)*invden
logistic = r*Nsym*(1 - Nsym/K)
deathP = m*Psym
gainP  = e*pred

feature_syms = [
    sp.Integer(1), Nsym, Psym,
    Nsym**2, Psym**2, Nsym*Psym,
    denom, invden, fN,
    logistic, pred, gainP, deathP,
    r*Nsym, (Nsym/K), r*Nsym*(Nsym/K),
    a*Nsym, a*Psym, a*Nsym*Psym,
    a*h*Nsym, (a*h*Nsym)*Psym,
]

# Normalization-aware substitution: vars_i -> (Theta_i - mu_i)/sd_i
mu = X_mean.detach().cpu().numpy().reshape(-1)
sd = X_std.detach().cpu().numpy().reshape(-1)
feature_syms_norm = [(feature_syms[i] - sp.Float(mu[i])) / sp.Float(sd[i]) for i in range(n_in)]
sub_map = {vars_[i]: feature_syms_norm[i] for i in range(n_in)}

def round_numbers(expr, places=5):
    repl = {}
    for aa in expr.atoms(sp.Number):
        try:
            repl[aa] = sp.Float(round(float(aa), places))
        except Exception:
            pass
    return expr.xreplace(repl)

def flatten(obj):
    if isinstance(obj, (list, tuple)):
        out = []
        for it in obj:
            out.extend(flatten(it))
        return out
    return [obj]

exprs_list = flatten(exprs_raw)

cleaned = []
for expr in exprs_list:
    if not hasattr(expr, "free_symbols"):
        continue
    ex = expr.subs(sub_map)
    ex = sp.together(sp.expand(ex))
    ex = round_numbers(ex, 5)
    cleaned.append(ex)

# Display discovered RHS equations (dN/dt, dP/dt)
dNdt, dPdt = sp.symbols(r"\dot{N} \dot{P}")
if len(cleaned) >= 2:
    display(Math(latex(Eq(dNdt, cleaned[0]))))
    display(Math(latex(Eq(dPdt, cleaned[1]))))
else:
    for k, ex in enumerate(cleaned):
        display(Math(latex(Eq(sp.Symbol(f"out_{k}"), ex))))

print("\nTrue Holling-II RHS:")
print("dN/dt = r N (1 - N/K) - (a N P)/(1 + a h N)")
print("dP/dt = e (a N P)/(1 + a h N) - m P")
print("dt used for rollouts =", dt)

# ============================================================
# Holling Type II discovery w/ physics-informed wide features + zero-depth KAN
# TRAINING ON DERIVATIVES (RHS) INSTEAD OF ONE-STEP MAP
# - Simulate trajectories (RK4) to get state samples
# - Labels are true derivatives from the Holling-II RHS at those states
# - Train KAN: Theta(N,P) -> (dN/dt, dP/dt)
# - Optional multi-step rollout loss via Euler (or RK4) integrating predicted derivatives
# - Symbolic extraction w/ complexity DOWN-WEIGHTED for physics-informed features
# ============================================================

import numpy as np
import torch
import matplotlib.pyplot as plt

import sympy as sp
from sympy import Eq
from sympy.printing.latex import latex
from IPython.display import display, Math

from kan import KAN

# -----------------------
# Repro / device
# -----------------------
seed = 42
rng = np.random.default_rng(seed)
torch.manual_seed(seed)
np.random.seed(seed)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

def to_tensor(a):
    return torch.tensor(a, dtype=torch.float32, device=device)

# ============================================================
# Holling Type II predator-prey ODE (Rosenzweig–MacArthur)
# dN/dt = r N (1 - N/K) - (a N P)/(1 + a h N)
# dP/dt = e (a N P)/(1 + a h N) - m P
# ============================================================

def holling_rhs_np(state, r, K, a, h, e, m):
    N, P = state
    denom = 1.0 + a*h*N
    pred  = (a*N*P) / denom
    dN = r*N*(1.0 - N/K) - pred
    dP = e*pred - m*P
    return np.array([dN, dP], dtype=np.float32)

def rk4_step_np(state, dt, r, K, a, h, e, m):
    k1 = holling_rhs_np(state, r,K,a,h,e,m)
    k2 = holling_rhs_np(state + 0.5*dt*k1, r,K,a,h,e,m)
    k3 = holling_rhs_np(state + 0.5*dt*k2, r,K,a,h,e,m)
    k4 = holling_rhs_np(state + dt*k3, r,K,a,h,e,m)
    return (state + (dt/6.0)*(k1 + 2*k2 + 2*k3 + k4)).astype(np.float32)

def generate_holling_traj_np(
    n_total=3000,
    burn_in=200,
    dt=0.02,
    x0=(10.0, 5.0),
    params=(1.0, 50.0, 1.2, 0.1, 0.6, 0.4),
    noise_std=0.0
):
    r, K, a, h, e, m = params
    T = n_total + burn_in
    traj = np.zeros((T, 2), dtype=np.float32)
    traj[0] = np.array(x0, dtype=np.float32)

    for i in range(T - 1):
        traj[i+1] = rk4_step_np(traj[i], dt, r,K,a,h,e,m)
        if noise_std > 0:
            traj[i+1] += rng.normal(0.0, noise_std, size=(2,)).astype(np.float32)
        traj[i+1] = np.maximum(traj[i+1], 0.0)
    return traj[burn_in:]

# ============================================================
# Physics-informed feature library (NumPy)
# ============================================================

def build_holling_features_np(N, P, *, r, K, a, h, e, m):
    one = np.ones_like(N)

    denom  = 1.0 + a*h*N
    invden = 1.0 / denom
    fN     = N * invden
    pred   = (a*N*P) * invden
    logistic = r*N*(1.0 - N/K)
    deathP   = m*P
    gainP    = e*pred

    feats = [
        one, N, P,
        N*N, P*P, N*P,
        denom, invden, fN,
        logistic, pred, gainP, deathP,
        # optional aligned combos
        r*N, (N/K), r*N*(N/K),
        a*N, a*P, (a*N*P),
        (a*h*N), (a*h*N)*P,
    ]

    names = [
        "1","N","P",
        "N^2","P^2","N*P",
        "denom","invden","fN",
        "logistic","pred","gainP","deathP",
        "r*N","N/K","r*N*(N/K)",
        "a*N","a*P","a*N*P",
        "a*h*N","(a*h*N)*P",
    ]
    Theta = np.stack(feats, axis=-1).astype(np.float32)
    return Theta, names

# ============================================================
# Physics-informed feature library (Torch)
# ============================================================

def build_holling_features_torch(state_NP, *, r, K, a, h, e, m):
    N = state_NP[:, 0]
    P = state_NP[:, 1]
    one = torch.ones_like(N)

    denom  = 1.0 + a*h*N
    invden = 1.0 / denom
    fN     = N * invden
    pred   = (a*N*P) * invden
    logistic = r*N*(1.0 - N/K)
    deathP   = m*P
    gainP    = e*pred

    feats = torch.stack([
        one, N, P,
        N*N, P*P, N*P,
        denom, invden, fN,
        logistic, pred, gainP, deathP,
        r*N, (N/K), r*N*(N/K),
        a*N, a*P, (a*N*P),
        (a*h*N), (a*h*N)*P,
    ], dim=1)
    return feats  # (B,F)

# ============================================================
# Build multi-trajectory dataset (recommended)
# ============================================================

# "True" parameters (used for data + physics features)
r_true = 1.0
K_true = 50.0
a_true = 1.2
h_true = 0.1
e_true = 0.6
m_true = 0.4

dt = 0.02

def make_dataset_multi_ic_rhs(
    M=50, n_total=3000, burn_in=200, dt=0.02,
    N_range=(1.0, 60.0), P_range=(0.5, 30.0),
    params=(r_true, K_true, a_true, h_true, e_true, m_true),
    noise_std=0.0,
):
    r_,K_,a_,h_,e_,m_ = params
    X_list, dX_list, traj_list = [], [], []

    for _ in range(M):
        N0 = rng.uniform(*N_range)
        P0 = rng.uniform(*P_range)
        traj = generate_holling_traj_np(
            n_total=n_total, burn_in=burn_in, dt=dt,
            x0=(N0, P0),
            params=(r_,K_,a_,h_,e_,m_),
            noise_std=noise_std
        )
        # states
        X = traj[:-1].astype(np.float32)
        # true derivatives at those states
        dX = np.stack([holling_rhs_np(s, r_,K_,a_,h_,e_,m_) for s in X], axis=0).astype(np.float32)

        X_list.append(X)
        dX_list.append(dX)
        traj_list.append(traj.astype(np.float32))

    X_state = np.concatenate(X_list, axis=0)
    dXdt    = np.concatenate(dX_list, axis=0)
    # Keep trajectories for rollout eval/loss if desired
    return X_state, dXdt, traj_list

X_state, dXdt, traj_list = make_dataset_multi_ic_rhs(
    M=50, n_total=3000, burn_in=200, dt=dt,
    N_range=(1.0, 60.0), P_range=(0.5, 30.0),
    noise_std=0.0
)

Theta_np, feat_names = build_holling_features_np(
    X_state[:,0], X_state[:,1],
    r=r_true, K=K_true, a=a_true, h=h_true, e=e_true, m=m_true
)

print("Samples:", X_state.shape[0], " | Feature count:", Theta_np.shape[1])
print("First 10 features:", feat_names[:10])

# ============================================================
# Random split (not temporal now; data are pooled from multiple ICs)
# ============================================================

N = Theta_np.shape[0]
idx_all = np.arange(N)
rng.shuffle(idx_all)

test_frac = 0.2
val_frac  = 0.2
n_test = int(N * test_frac)
n_val  = int((N - n_test) * val_frac)

idx_test = idx_all[:n_test]
idx_val  = idx_all[n_test:n_test+n_val]
idx_train= idx_all[n_test+n_val:]

Theta_train = Theta_np[idx_train]
Y_train     = dXdt[idx_train]

Theta_val = Theta_np[idx_val]
Y_val     = dXdt[idx_val]

Theta_test = Theta_np[idx_test]
Y_test     = dXdt[idx_test]

Theta_train_t = to_tensor(Theta_train)
Y_train_t     = to_tensor(Y_train)
Theta_val_t   = to_tensor(Theta_val)
Y_val_t       = to_tensor(Y_val)
Theta_test_t  = to_tensor(Theta_test)
Y_test_t      = to_tensor(Y_test)

X_state_train = to_tensor(X_state[idx_train])
X_state_val   = to_tensor(X_state[idx_val])
X_state_test  = to_tensor(X_state[idx_test])

# ============================================================
# Normalize features
# ============================================================

X_mean = Theta_train_t.mean(dim=0, keepdim=True)
X_std  = Theta_train_t.std(dim=0, keepdim=True) + 1e-8

def normalize_feats(Theta_t):
    return (Theta_t - X_mean) / X_std

Theta_train_n = normalize_feats(Theta_train_t)
Theta_val_n   = normalize_feats(Theta_val_t)
Theta_test_n  = normalize_feats(Theta_test_t)

# ============================================================
# Model: zero-depth KAN learns RHS: Theta(N,P) -> (dN/dt, dP/dt)
# ============================================================

F = Theta_train_n.shape[1]
model = KAN(width=[F, 2], grid=5, k=3, base_fun='zero', seed=seed).to(device)

def rhs_fn_from_state(state_NP):
    Theta = build_holling_features_torch(
        state_NP, r=r_true, K=K_true, a=a_true, h=h_true, e=e_true, m=m_true
    )
    Theta_n = (Theta - X_mean) / X_std
    return model(Theta_n)  # (B,2) derivative prediction

# ============================================================
# Optional rollout loss: integrate predicted RHS forward
# (Euler shown; you can swap to RK4 in torch if you want)
# ============================================================

def rollout_loss_rhs(traj, horizon=50, n_starts=256, dt=0.02):
    """
    traj: (T,2) torch trajectory from simulator
    Roll forward using predicted RHS + Euler:
      s_{k+1} = s_k + dt * f_theta(s_k)
    Compare to true states along the trajectory.
    """
    T = traj.shape[0]
    if T <= horizon + 1:
        return torch.tensor(0.0, device=device)

    idx0 = torch.randint(0, T - horizon - 1, (n_starts,), device=device)
    s = traj[idx0]  # (B,2)
    loss = 0.0
    for k in range(1, horizon + 1):
        ds = rhs_fn_from_state(s)
        s  = s + dt * ds
        s  = torch.clamp(s, min=0.0)  # keep nonnegative
        s_true = traj[idx0 + k]
        loss = loss + torch.mean((s - s_true) ** 2)
    return loss / horizon

# Use one or more simulator trajectories for rollout loss
train_roll_traj = to_tensor(traj_list[0])  # pick one; you can cycle or concatenate if desired

# ============================================================
# Training loop
# ============================================================

steps = 3000
lr = 2e-3
batch_size = 4096

rollout_weight  = 0.3     # set 0 to disable
rollout_horizon = 60
rollout_starts  = 512

opt = torch.optim.Adam(model.parameters(), lr=lr)

best_val = float("inf")
best_state = None

for it in range(1, steps + 1):
    model.train()

    idx = torch.randint(0, Theta_train_n.shape[0], (batch_size,), device=device)
    pred = model(Theta_train_n[idx])              # predicted derivatives
    loss_1 = torch.mean((pred - Y_train_t[idx])**2)

    loss_r = rollout_loss_rhs(
        train_roll_traj, horizon=rollout_horizon, n_starts=rollout_starts, dt=dt
    ) if rollout_weight > 0 else 0.0

    loss = (1.0 - rollout_weight) * loss_1 + rollout_weight * loss_r

    opt.zero_grad(set_to_none=True)
    loss.backward()
    opt.step()

    if it % 100 == 0 or it == 1:
        model.eval()
        with torch.no_grad():
            val_pred = model(Theta_val_n)
            val_mse = torch.mean((val_pred - Y_val_t)**2).item()
        if val_mse < best_val:
            best_val = val_mse
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        print(f"step {it:5d} | loss={loss.item():.3e} | rhs_mse={loss_1.item():.3e} | roll={float(loss_r):.3e} | val_mse={val_mse:.3e}")

if best_state is not None:
    model.load_state_dict({k: v.to(device) for k, v in best_state.items()})
print("Best val mse:", best_val)

# ============================================================
# Test metrics (RHS prediction)
# ============================================================

model.eval()
with torch.no_grad():
    test_pred = model(Theta_test_n)
    test_mse = torch.mean((test_pred - Y_test_t)**2).item()
print("Test RHS MSE:", test_mse)

# Sensitivity sanity check: does predicted RHS depend on both N and P?
with torch.no_grad():
    P0 = torch.tensor([[5.0]], device=device)
    Ns = torch.linspace(1.0, 40.0, 200, device=device).unsqueeze(1)
    states = torch.cat([Ns, P0.repeat(Ns.shape[0],1)], dim=1)
    out = rhs_fn_from_state(states)
    print("var(dN/dt) over N (P fixed):", out[:,0].var().item())
    print("var(dP/dt) over N (P fixed):", out[:,1].var().item())

# ============================================================
# Rollout eval (integrate predicted RHS) on a fresh simulator trajectory
# ============================================================

def rollout_eval_rhs(traj, horizon=800, dt=0.02):
    """
    traj: (T,2) torch truth trajectory
    Start from traj[0], integrate predicted RHS forward, compare
    """
    s = traj[0:1]  # (1,2)
    preds = [s]
    for _ in range(horizon):
        ds = rhs_fn_from_state(s)
        s = s + dt * ds
        s = torch.clamp(s, min=0.0)
        preds.append(s)
    preds = torch.cat(preds, dim=0)
    truth = traj[:horizon+1]
    return preds, truth

test_traj = to_tensor(traj_list[-1])  # another trajectory
with torch.no_grad():
    pred_roll, true_roll = rollout_eval_rhs(test_traj, horizon=800, dt=dt)
    roll_mse = torch.mean((pred_roll - true_roll)**2).item()
print("Rollout MSE (state space):", roll_mse)

pred_np = pred_roll.detach().cpu().numpy()
true_np = true_roll.detach().cpu().numpy()

plt.figure()
plt.plot(true_np[:,0], label="true N")
plt.plot(pred_np[:,0], label="pred N", alpha=0.8)
plt.legend()
plt.title("Holling-II rollout from learned RHS: prey")
plt.show()

plt.figure()
plt.plot(true_np[:,1], label="true P")
plt.plot(pred_np[:,1], label="pred P", alpha=0.8)
plt.legend()
plt.title("Holling-II rollout from learned RHS: predator")
plt.show()

plt.figure()
plt.plot(true_np[:,0], true_np[:,1], label="true")
plt.plot(pred_np[:,0], pred_np[:,1], label="pred", alpha=0.8)
plt.legend()
plt.title("Holling-II phase portrait rollout (learned RHS)")
plt.show()

# ============================================================
# Symbolic extraction w/ physics features down-weighted (preferred)
# ============================================================

model.save_act = True
_ = model(Theta_train_n[:2048])

PHYS_SYMBOLIC_LIB = {
    'x':   (lambda x: x,    lambda x: x,          1, lambda x, y_th: ((), x)),
    'x^2': (lambda x: x**2, lambda x: x**2,       2, lambda x, y_th: ((), x**2)),
    'x^3': (lambda x: x**3, lambda x: x**3,       3, lambda x, y_th: ((), x**3)),
    '0':   (lambda x: x*0,  lambda x: x*0,        0, lambda x, y_th: ((), x*0)),
}

GEN_SYMBOLIC_LIB = {
    'x':   (lambda x: x,    lambda x: x,          3, lambda x, y_th: ((), x)),
    'x^2': (lambda x: x**2, lambda x: x**2,       4, lambda x, y_th: ((), x**2)),
    'x^3': (lambda x: x**3, lambda x: x**3,       5, lambda x, y_th: ((), x**3)),
    '0':   (lambda x: x*0,  lambda x: x*0,        0, lambda x, y_th: ((), x*0)),
}

physics_idx = set([
    feat_names.index("denom"),
    feat_names.index("invden"),
    feat_names.index("fN"),
    feat_names.index("logistic"),
    feat_names.index("pred"),
    feat_names.index("gainP"),
    feat_names.index("deathP"),
])

def auto_symbolic_physics_preferred(
    self,
    a_range=(-10, 10),
    b_range=(-10, 10),
    weight_simple=0.8,
    r2_threshold=0.90,
    verbose=1
):
    for l in range(len(self.width_in) - 1):
        for i in range(self.width_in[l]):
            for j in range(self.width_out[l + 1]):
                lib = PHYS_SYMBOLIC_LIB if i in physics_idx else GEN_SYMBOLIC_LIB
                name, fun, r2, c = self.suggest_symbolic(
                    l, i, j,
                    a_range=a_range, b_range=b_range,
                    lib=lib,
                    verbose=False,
                    weight_simple=weight_simple
                )
                if r2 >= r2_threshold:
                    self.fix_symbolic(l, i, j, name, verbose=verbose > 1, log_history=False)
                    if verbose >= 1:
                        tag = "PHYS" if (i in physics_idx) else "GEN"
                        print(f'fixing ({l},{i},{j}) [{tag}] with {name}, r2={r2:.4f}, c={c}')
                else:
                    self.fix_symbolic(l, i, j, '0', verbose=verbose > 1, log_history=False)
                    if verbose >= 1:
                        print(f'omit ({l},{i},{j}) best={name}, r2={r2:.4f} < {r2_threshold}, set to 0')
    self.log_history('auto_symbolic_physics_preferred')

auto_symbolic_physics_preferred(model, weight_simple=0.7, r2_threshold=0.90, verbose=1)

# ============================================================
# Extract symbolic RHS and substitute semantic meanings of inputs
# IMPORTANT: symbolic_formula uses normalized inputs -> substitute normalized feature symbols
# ============================================================

exprs_raw, vars_ = model.symbolic_formula()
n_in = int(model.width_in[0])
if len(vars_) < n_in:
    raise ValueError(f"symbolic_formula returned only {len(vars_)} vars, but model has n_in={n_in}")

# SymPy state + params
Nsym, Psym = sp.symbols("N P", real=True, nonnegative=True)
r, K, a, h, e, m = sp.symbols("r K a h e m", real=True)

denom  = 1 + a*h*Nsym
invden = 1/denom
fN     = Nsym*invden
pred   = (a*Nsym*Psym)*invden
logistic = r*Nsym*(1 - Nsym/K)
deathP = m*Psym
gainP  = e*pred

feature_syms = [
    sp.Integer(1), Nsym, Psym,
    Nsym**2, Psym**2, Nsym*Psym,
    denom, invden, fN,
    logistic, pred, gainP, deathP,
    r*Nsym, (Nsym/K), r*Nsym*(Nsym/K),
    a*Nsym, a*Psym, a*Nsym*Psym,
    a*h*Nsym, (a*h*Nsym)*Psym,
]

# Normalization-aware substitution: vars_i -> (Theta_i - mu_i)/sd_i
mu = X_mean.detach().cpu().numpy().reshape(-1)
sd = X_std.detach().cpu().numpy().reshape(-1)
feature_syms_norm = [(feature_syms[i] - sp.Float(mu[i])) / sp.Float(sd[i]) for i in range(n_in)]
sub_map = {vars_[i]: feature_syms_norm[i] for i in range(n_in)}

def round_numbers(expr, places=5):
    repl = {}
    for aa in expr.atoms(sp.Number):
        try:
            repl[aa] = sp.Float(round(float(aa), places))
        except Exception:
            pass
    return expr.xreplace(repl)

def flatten(obj):
    if isinstance(obj, (list, tuple)):
        out = []
        for it in obj:
            out.extend(flatten(it))
        return out
    return [obj]

exprs_list = flatten(exprs_raw)

cleaned = []
for expr in exprs_list:
    if not hasattr(expr, "free_symbols"):
        continue
    ex = expr.subs(sub_map)
    ex = sp.together(sp.expand(ex))
    ex = round_numbers(ex, 5)
    cleaned.append(ex)

# Display discovered RHS equations (dN/dt, dP/dt)
dNdt, dPdt = sp.symbols(r"\dot{N} \dot{P}")
if len(cleaned) >= 2:
    display(Math(latex(Eq(dNdt, cleaned[0]))))
    display(Math(latex(Eq(dPdt, cleaned[1]))))
else:
    for k, ex in enumerate(cleaned):
        display(Math(latex(Eq(sp.Symbol(f"out_{k}"), ex))))

print("\nTrue Holling-II RHS:")
print("dN/dt = r N (1 - N/K) - (a N P)/(1 + a h N)")
print("dP/dt = e (a N P)/(1 + a h N) - m P")
print("dt used for rollouts =", dt)

