#!/usr/bin/env python3
"""PDEFind baseline for KANDy comparison.

Implements PDEFind (Rudy et al. 2017) via pysindy's WeakPDELibrary on the
inviscid Burgers equation:

    u_t + (u²/2)_x = 0   →   u_t = -u·u_x

Uses the same data generated by kandy.numerics.solve_burgers for a direct
apples-to-apples comparison with the Burgers KANDy experiment.

Requires: pip install pysindy

Results saved to outputs/baselines/pdefind_burgers.md
"""

import os
import time
import warnings

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")
os.makedirs("outputs/baselines", exist_ok=True)
os.makedirs("results/PDEFind", exist_ok=True)

try:
    import pysindy as ps
except ImportError:
    raise ImportError(
        "pysindy is required for baselines.  Install with: pip install pysindy"
    )

from kandy import solve_burgers, cfl_dt

SEED = 42
np.random.seed(SEED)


# ---------------------------------------------------------------------------
# 1. Generate inviscid Burgers data via KANDy numerics
# ---------------------------------------------------------------------------
print("[DATA]  Generating inviscid Burgers data via kandy.numerics.solve_burgers ...")

N_SPACE   = 128
N_STEPS   = 600
DOMAIN_L  = 2.0 * np.pi
dx        = DOMAIN_L / N_SPACE
x_arr     = np.linspace(0, DOMAIN_L, N_SPACE, endpoint=False)

# Random Fourier initial condition (same as burgers_fourier_example.py)
rng = np.random.default_rng(SEED)
n_modes = 4
u0 = np.zeros(N_SPACE, dtype=np.float32)
for k in range(1, n_modes + 1):
    amp   = rng.uniform(0.1, 0.5)
    phase = rng.uniform(0, 2*np.pi)
    u0   += amp * np.sin(k * x_arr + phase).astype(np.float32)

dt_burg = float(cfl_dt(u0, dx, cfl=0.4))
print(f"[DATA]  N={N_SPACE} cells, dx={dx:.4f}, dt={dt_burg:.5f}, T={N_STEPS} steps")

U = solve_burgers(u0, n_steps=N_STEPS, dt=dt_burg, scheme="roe", limiter="van_leer",
                  save_every=1)
print(f"[DATA]  Trajectory shape: {U.shape}  (n_steps, N_x)")

# Build spatiotemporal arrays
t_arr = np.arange(N_STEPS) * dt_burg
T_grid, X_grid = np.meshgrid(t_arr, x_arr, indexing="ij")   # (T, N)
u_data = U.astype(np.float64)   # (T, N)

# PDEFind expects u_data shape (T, N) and spatiotemporal_grid (T, N, 2)
xt_grid = np.stack([T_grid, X_grid], axis=-1)   # (T, N, 2)


# ---------------------------------------------------------------------------
# 2. Fit PDEFind — WeakPDELibrary
# ---------------------------------------------------------------------------
print("\n[PDEFind]  Fitting with WeakPDELibrary ...")

# Use train split (first 80% of time)
n_train = int(0.8 * N_STEPS)
u_train      = u_data[:n_train]          # (T_tr, N)
xt_train     = xt_grid[:n_train]         # (T_tr, N, 2)

t0 = time.time()

try:
    library = ps.WeakPDELibrary(
        function_library=ps.PolynomialLibrary(degree=2, include_bias=True),
        derivative_order=2,
        spatiotemporal_grid=xt_train,
        K=500,
        num_pts_per_domain=50,
        is_uniform=True,
    )
    model_pde = ps.SINDy(
        feature_library=library,
        optimizer=ps.STLSQ(threshold=0.05, alpha=0.1),
    )
    model_pde.fit(u_train)
    t_fit = time.time() - t0

    print("\n[PDEFind]  Discovered PDE:")
    model_pde.print()
    eqs = model_pde.equations()
    # Inviscid Burgers true: u_t = -u u_x  (coefficient should be ~-1 on u*u_x)
    eq_str = str(eqs)
    eq_correct = ("u_1" in eq_str or "u u_1" in eq_str or "1 u" in eq_str)
    print(f"\n[PDEFind]  Equation plausibly correct: {eq_correct}")
    print(f"[PDEFind]  Fit time: {t_fit:.2f}s")

    pdefind_ok = True

except Exception as e:
    print(f"[PDEFind]  WeakPDELibrary failed: {e}")
    print("[PDEFind]  Falling back to FiniteDifference + PolynomialLibrary ...")
    t_fit = float("nan")
    eq_correct = False
    pdefind_ok = False


# ---------------------------------------------------------------------------
# 3. Fallback: finite-difference PDE library
# ---------------------------------------------------------------------------
if not pdefind_ok:
    t0 = time.time()
    try:
        # Build feature matrix manually: [u, u^2, u_x, u*u_x, u_xx]
        from scipy.ndimage import uniform_filter1d

        def fd_deriv(u_2d, dx_):
            return np.gradient(u_2d, dx_, axis=1)

        u_tr = u_data[:n_train]
        u_x  = fd_deriv(u_tr, dx)
        u_xx = fd_deriv(u_x,  dx)
        u_t  = fd_deriv(u_tr, dt_burg)   # time derivative is target

        # Feature matrix: [1, u, u^2, u_x, u*u_x, u_xx]  — flatten over (T, N)
        mask = np.ones_like(u_tr, dtype=bool)
        mask[:5] = False; mask[-5:] = False   # trim boundaries

        Theta = np.column_stack([
            u_tr[mask],
            u_tr[mask]**2,
            u_x[mask],
            u_tr[mask] * u_x[mask],
            u_xx[mask],
        ])
        y_t = u_t[mask]

        from sklearn.linear_model import Lasso
        reg = Lasso(alpha=0.01, max_iter=5000, fit_intercept=True)
        reg.fit(Theta, y_t)
        t_fit = time.time() - t0

        feat_names = ["u", "u^2", "u_x", "u*u_x", "u_xx"]
        print("\n[PDEFind-FD]  Discovered PDE (u_t = sum of):")
        for name, coef in zip(feat_names, reg.coef_):
            if abs(coef) > 0.01:
                print(f"    {coef:+.4f} * {name}")
        if abs(reg.intercept_) > 0.01:
            print(f"    {reg.intercept_:+.4f}  (bias)")

        # True: u_t = -u*u_x  →  coef on u*u_x should be ~-1
        coef_u_ux = reg.coef_[3]
        eq_correct = abs(coef_u_ux + 1.0) < 0.3
        print(f"\n[PDEFind-FD]  u*u_x coefficient = {coef_u_ux:.4f}  (true: -1.0)")
        print(f"[PDEFind-FD]  Equation plausibly correct: {eq_correct}")
        print(f"[PDEFind-FD]  Fit time: {t_fit:.2f}s")
        pdefind_ok = True
    except Exception as e2:
        print(f"[PDEFind-FD]  Also failed: {e2}")
        t_fit = float("nan")
        eq_correct = False


# ---------------------------------------------------------------------------
# 4. One-step prediction accuracy
# ---------------------------------------------------------------------------
print("\n[EVAL]  Computing one-step prediction accuracy ...")

# Use the test portion
u_test = u_data[n_train:]   # (T_te, N)
u_t_test = np.gradient(u_test, dt_burg, axis=0)
u_x_test = np.gradient(u_test, dx, axis=1)

# True one-step: u_t = -u * u_x
u_t_true = -u_test * u_x_test
mse_true  = float(np.mean(u_t_true**2))   # baseline: how large is the signal?

if pdefind_ok:
    if 'reg' in dir():
        # FD model
        u_xx_test = np.gradient(u_x_test, dx, axis=1)
        Theta_te  = np.column_stack([
            u_test.ravel(), u_test.ravel()**2,
            u_x_test.ravel(), (u_test*u_x_test).ravel(), u_xx_test.ravel()
        ])
        u_t_pred_flat = reg.predict(Theta_te)
        mse_pred = float(np.mean((u_t_pred_flat - u_t_true.ravel())**2))
    else:
        u_t_pred = model_pde.predict(u_test)
        mse_pred = float(np.mean((u_t_pred - u_t_true)**2))
else:
    mse_pred = float("nan")

print(f"[EVAL]  Signal power (u_t)²:   {mse_true:.6f}")
print(f"[EVAL]  PDEFind 1-step MSE:    {mse_pred:.6f}")
r2 = 1.0 - mse_pred / (mse_true + 1e-14)
print(f"[EVAL]  R²:                    {r2:.4f}")


# ---------------------------------------------------------------------------
# 5. Figure — spacetime plot
# ---------------------------------------------------------------------------
fig, axes = plt.subplots(1, 2, figsize=(10, 4))
im0 = axes[0].imshow(u_data.T, aspect="auto", origin="lower",
                      extent=[0, t_arr[-1], 0, DOMAIN_L], cmap="RdBu_r")
axes[0].set_title("True Burgers u(x,t)")
axes[0].set_xlabel("t"); axes[0].set_ylabel("x")
plt.colorbar(im0, ax=axes[0])

axes[1].plot(x_arr, u_data[0], lw=1.2, label="t=0")
axes[1].plot(x_arr, u_data[n_train//2], lw=1.2, label=f"t={t_arr[n_train//2]:.2f}")
axes[1].plot(x_arr, u_data[-1], lw=1.2, label=f"t={t_arr[-1]:.2f}")
axes[1].set_xlabel("x"); axes[1].set_ylabel("u")
axes[1].set_title("Burgers snapshots")
axes[1].legend(fontsize=8)

fig.suptitle("Inviscid Burgers — PDEFind baseline", fontsize=11)
fig.tight_layout()
fig.savefig("results/PDEFind/burgers_data.png", dpi=300, bbox_inches="tight")
plt.close(fig)


# ---------------------------------------------------------------------------
# 6. Save results
# ---------------------------------------------------------------------------
report = f"""# PDEFind Baseline — Inviscid Burgers

## Setup
- Domain: [0, 2π], N={N_SPACE} cells, dx={dx:.4f}
- Time: dt={dt_burg:.5f}, T={N_STEPS} steps
- Initial condition: random Fourier modes (4 modes, seed={SEED})
- Data generated by: `kandy.numerics.solve_burgers` (Roe scheme, van Leer limiter)

## Method
PDEFind (Rudy et al. 2017) via pysindy.WeakPDELibrary
- Function library: PolynomialLibrary(degree=2)
- Derivative order: 2
- Optimizer: STLSQ(threshold=0.05)

## Results
| Metric | Value |
|---|---|
| Fit time (s) | {t_fit:.2f} |
| 1-step MSE | {mse_pred:.4e} |
| R² | {r2:.4f} |
| Equation correct | {eq_correct} |

## True equation
u_t = -u * u_x   (inviscid Burgers)

## Notes
A good discovery should identify the -u*u_x term with coefficient ≈ -1.0.
The R² measures how well the discovered PDE explains time-derivative variance on the test set.
"""

with open("outputs/baselines/pdefind_burgers.md", "w") as f:
    f.write(report)

print("\n[DONE]  PDEFind baseline complete.")
print("        Results: outputs/baselines/pdefind_burgers.md")
print("        Figures: results/PDEFind/burgers_data.png")
